// Autogenerated file
// Do not manually modify
// file:./database/loudatabase.h



#ifndef	__LOUDATABASE_H_H
#define	__LOUDATABASE_H_H


#define	LOU_DBFILE_NBR	456
#define	LOU_DATABASE_INFO_NBR	234
#define	LOU_DATABASE_DISPLAY_NBR	26


typedef struct _lou_dbfile{
	char *fname;
	uint8_t* data;
	size_t* size;
	uint8_t* bzdata;
	size_t* bzsize;
	size_t bzusize;
} lou_dbfile;


typedef struct _lou_dbfile_info{
	char     *fname;
	char     *desc;
	char     *lang;
	char     *region;
	uint16_t  flags;
} lou_dbfile_info;
#endif


