// Autogenerated file
// Do not manually modify
// file:./liblouisreact/database/loudatabase.c


#include <stdio.h>
#include <stdlib.h>
#ifdef __EMSCRIPTEN__
#include "emscripten.h"
#define EXPORT_CALL EMSCRIPTEN_KEEPALIVE
#endif

#include "loudatabase.h"


extern uint8_t afr__za__g1__ctb[];
extern size_t afr__za__g1__ctb_size;
extern uint8_t afr__za__g2__ctb[];
extern size_t afr__za__g2__ctb_size;
extern uint8_t ar__ar__comp8__utb[];
extern size_t ar__ar__comp8__utb_size;
extern uint8_t ar__ar__g1__core__uti[];
extern size_t ar__ar__g1__core__uti_size;
extern uint8_t ar__ar__g1__utb[];
extern size_t ar__ar__g1__utb_size;
extern uint8_t ar__ar__g2__ctb[];
extern size_t ar__ar__g2__ctb_size;
extern uint8_t ar__ar__math__uti[];
extern size_t ar__ar__math__uti_size;
extern uint8_t ar__tbl[];
extern size_t ar__tbl_size;
extern uint8_t as__in__g1__utb[];
extern size_t as__in__g1__utb_size;
extern uint8_t as__tbl[];
extern size_t as__tbl_size;
extern uint8_t aw__in__g1__utb[];
extern size_t aw__in__g1__utb_size;
extern uint8_t awa__tbl[];
extern size_t awa__tbl_size;
extern uint8_t ba__utb[];
extern size_t ba__utb_size;
extern uint8_t be__in__g1__utb[];
extern size_t be__in__g1__utb_size;
extern uint8_t bel__comp__utb[];
extern size_t bel__comp__utb_size;
extern uint8_t bel__utb[];
extern size_t bel__utb_size;
extern uint8_t bengali__cti[];
extern size_t bengali__cti_size;
extern uint8_t bg__ctb[];
extern size_t bg__ctb_size;
extern uint8_t bg__dis[];
extern size_t bg__dis_size;
extern uint8_t bg__tbl[];
extern size_t bg__tbl_size;
extern uint8_t bg__utb[];
extern size_t bg__utb_size;
extern uint8_t bh__ctb[];
extern size_t bh__ctb_size;
extern uint8_t bh__tbl[];
extern size_t bh__tbl_size;
extern uint8_t bn__tbl[];
extern size_t bn__tbl_size;
extern uint8_t bo__ctb[];
extern size_t bo__ctb_size;
extern uint8_t bo__tbl[];
extern size_t bo__tbl_size;
extern uint8_t boxes__ctb[];
extern size_t boxes__ctb_size;
extern uint8_t br__in__g1__utb[];
extern size_t br__in__g1__utb_size;
extern uint8_t bra__tbl[];
extern size_t bra__tbl_size;
extern uint8_t braille__patterns__cti[];
extern size_t braille__patterns__cti_size;
extern uint8_t ca__chardefs__cti[];
extern size_t ca__chardefs__cti_size;
extern uint8_t ca__g1__ctb[];
extern size_t ca__g1__ctb_size;
extern uint8_t ca__tbl[];
extern size_t ca__tbl_size;
extern uint8_t chr__us__g1__ctb[];
extern size_t chr__us__g1__ctb_size;
extern uint8_t ckb__chardefs__cti[];
extern size_t ckb__chardefs__cti_size;
extern uint8_t ckb__g1__ctb[];
extern size_t ckb__g1__ctb_size;
extern uint8_t ckb__translation__cti[];
extern size_t ckb__translation__cti_size;
extern uint8_t ckb__tbl[];
extern size_t ckb__tbl_size;
extern uint8_t compress__cti[];
extern size_t compress__cti_size;
extern uint8_t controlchars__cti[];
extern size_t controlchars__cti_size;
extern uint8_t cop__eg__comp8__utb[];
extern size_t cop__eg__comp8__utb_size;
extern uint8_t corrections__cti[];
extern size_t corrections__cti_size;
extern uint8_t countries__cti[];
extern size_t countries__cti_size;
extern uint8_t cs__chardefs__cti[];
extern size_t cs__chardefs__cti_size;
extern uint8_t cs__comp8__utb[];
extern size_t cs__comp8__utb_size;
extern uint8_t cs__g1__ctb[];
extern size_t cs__g1__ctb_size;
extern uint8_t cs__translation__cti[];
extern size_t cs__translation__cti_size;
extern uint8_t cs__tbl[];
extern size_t cs__tbl_size;
extern uint8_t cy__cy__g1__utb[];
extern size_t cy__cy__g1__utb_size;
extern uint8_t cy__cy__g2__ctb[];
extern size_t cy__cy__g2__ctb_size;
extern uint8_t cy__tbl[];
extern size_t cy__tbl_size;
extern uint8_t da__dk__6miscChars__cti[];
extern size_t da__dk__6miscChars__cti_size;
extern uint8_t da__dk__6miscChars_1993__cti[];
extern size_t da__dk__6miscChars_1993__cti_size;
extern uint8_t da__dk__8miscChars__cti[];
extern size_t da__dk__8miscChars__cti_size;
extern uint8_t da__dk__8miscChars_1993__cti[];
extern size_t da__dk__8miscChars_1993__cti_size;
extern uint8_t da__dk__g08__ctb[];
extern size_t da__dk__g08__ctb_size;
extern uint8_t da__dk__g08_1993__ctb[];
extern size_t da__dk__g08_1993__ctb_size;
extern uint8_t da__dk__g16__lit_1993__ctb[];
extern size_t da__dk__g16__lit_1993__ctb_size;
extern uint8_t da__dk__g16__ctb[];
extern size_t da__dk__g16__ctb_size;
extern uint8_t da__dk__g16_1993__ctb[];
extern size_t da__dk__g16_1993__ctb_size;
extern uint8_t da__dk__g18__ctb[];
extern size_t da__dk__g18__ctb_size;
extern uint8_t da__dk__g18_1993__ctb[];
extern size_t da__dk__g18_1993__ctb_size;
extern uint8_t da__dk__g2__dic[];
extern size_t da__dk__g2__dic_size;
extern uint8_t da__dk__g26__lit_1993__ctb[];
extern size_t da__dk__g26__lit_1993__ctb_size;
extern uint8_t da__dk__g26__ctb[];
extern size_t da__dk__g26__ctb_size;
extern uint8_t da__dk__g26_1993__ctb[];
extern size_t da__dk__g26_1993__ctb_size;
extern uint8_t da__dk__g26l__lit_1993__ctb[];
extern size_t da__dk__g26l__lit_1993__ctb_size;
extern uint8_t da__dk__g26l_1993__ctb[];
extern size_t da__dk__g26l_1993__ctb_size;
extern uint8_t da__dk__g28__ctb[];
extern size_t da__dk__g28__ctb_size;
extern uint8_t da__dk__g28_1993__ctb[];
extern size_t da__dk__g28_1993__ctb_size;
extern uint8_t da__dk__g28l_1993__ctb[];
extern size_t da__dk__g28l_1993__ctb_size;
extern uint8_t da__dk__g2_1993__dic[];
extern size_t da__dk__g2_1993__dic_size;
extern uint8_t da__dk__octobraille__dis[];
extern size_t da__dk__octobraille__dis_size;
extern uint8_t da__dk__octobraille_1993__dis[];
extern size_t da__dk__octobraille_1993__dis_size;
extern uint8_t de__accents__detailed__cti[];
extern size_t de__accents__detailed__cti_size;
extern uint8_t de__accents__cti[];
extern size_t de__accents__cti_size;
extern uint8_t de__chardefs6__cti[];
extern size_t de__chardefs6__cti_size;
extern uint8_t de__chardefs8__cti[];
extern size_t de__chardefs8__cti_size;
extern uint8_t de__chess__ctb[];
extern size_t de__chess__ctb_size;
extern uint8_t de__comp6__utb[];
extern size_t de__comp6__utb_size;
extern uint8_t de__de__comp8__ctb[];
extern size_t de__de__comp8__ctb_size;
extern uint8_t de__de__dis[];
extern size_t de__de__dis_size;
extern uint8_t de__eurobrl6__dis[];
extern size_t de__eurobrl6__dis_size;
extern uint8_t de__eurobrl6u__dis[];
extern size_t de__eurobrl6u__dis_size;
extern uint8_t de__g0__core__uti[];
extern size_t de__g0__core__uti_size;
extern uint8_t de__g0__detailed__utb[];
extern size_t de__g0__detailed__utb_size;
extern uint8_t de__g0__utb[];
extern size_t de__g0__utb_size;
extern uint8_t de__g1__core__patterns__dic[];
extern size_t de__g1__core__patterns__dic_size;
extern uint8_t de__g1__core__cti[];
extern size_t de__g1__core__cti_size;
extern uint8_t de__g1__detailed__ctb[];
extern size_t de__g1__detailed__ctb_size;
extern uint8_t de__g1__ctb[];
extern size_t de__g1__ctb_size;
extern uint8_t de__g2__core__patterns__dic[];
extern size_t de__g2__core__patterns__dic_size;
extern uint8_t de__g2__core__cti[];
extern size_t de__g2__core__cti_size;
extern uint8_t de__g2__detailed__ctb[];
extern size_t de__g2__detailed__ctb_size;
extern uint8_t de__g2__ctb[];
extern size_t de__g2__ctb_size;
extern uint8_t devanagari__cti[];
extern size_t devanagari__cti_size;
extern uint8_t digits6Dots__uti[];
extern size_t digits6Dots__uti_size;
extern uint8_t digits6DotsPlusDot6__uti[];
extern size_t digits6DotsPlusDot6__uti_size;
extern uint8_t digits8Dots__uti[];
extern size_t digits8Dots__uti_size;
extern uint8_t dra__ctb[];
extern size_t dra__ctb_size;
extern uint8_t dra__tbl[];
extern size_t dra__tbl_size;
extern uint8_t el__ctb[];
extern size_t el__ctb_size;
extern uint8_t en__chardefs__cti[];
extern size_t en__chardefs__cti_size;
extern uint8_t en__chess__ctb[];
extern size_t en__chess__ctb_size;
extern uint8_t en__gb__comp8__ctb[];
extern size_t en__gb__comp8__ctb_size;
extern uint8_t en__gb__g1__utb[];
extern size_t en__gb__g1__utb_size;
extern uint8_t en__GB__g2__ctb[];
extern size_t en__GB__g2__ctb_size;
extern uint8_t en__in__g1__ctb[];
extern size_t en__in__g1__ctb_size;
extern uint8_t en__nabcc__utb[];
extern size_t en__nabcc__utb_size;
extern uint8_t en__ueb__chardefs__uti[];
extern size_t en__ueb__chardefs__uti_size;
extern uint8_t en__ueb__g1__ctb[];
extern size_t en__ueb__g1__ctb_size;
extern uint8_t en__ueb__g2__ctb[];
extern size_t en__ueb__g2__ctb_size;
extern uint8_t en__ueb__math__ctb[];
extern size_t en__ueb__math__ctb_size;
extern uint8_t en__us__brf__dis[];
extern size_t en__us__brf__dis_size;
extern uint8_t en__us__comp6__ctb[];
extern size_t en__us__comp6__ctb_size;
extern uint8_t en__us__comp8__ext__utb[];
extern size_t en__us__comp8__ext__utb_size;
extern uint8_t en__us__comp8__ctb[];
extern size_t en__us__comp8__ctb_size;
extern uint8_t en__us__compbrl__uti[];
extern size_t en__us__compbrl__uti_size;
extern uint8_t en__us__emphasis__uti[];
extern size_t en__us__emphasis__uti_size;
extern uint8_t en__us__g1__ctb[];
extern size_t en__us__g1__ctb_size;
extern uint8_t en__us__g2__ctb[];
extern size_t en__us__g2__ctb_size;
extern uint8_t en__us__interline__ctb[];
extern size_t en__us__interline__ctb_size;
extern uint8_t en__us__mathtext__ctb[];
extern size_t en__us__mathtext__ctb_size;
extern uint8_t en_CA__ctb[];
extern size_t en_CA__ctb_size;
extern uint8_t en_CA__tbl[];
extern size_t en_CA__tbl_size;
extern uint8_t en_GB__tbl[];
extern size_t en_GB__tbl_size;
extern uint8_t en_US__comp8__ext__tbl[];
extern size_t en_US__comp8__ext__tbl_size;
extern uint8_t en_US__tbl[];
extern size_t en_US__tbl_size;
extern uint8_t eo__g1__x__system__ctb[];
extern size_t eo__g1__x__system__ctb_size;
extern uint8_t eo__g1__ctb[];
extern size_t eo__g1__ctb_size;
extern uint8_t eo__tbl[];
extern size_t eo__tbl_size;
extern uint8_t es__chardefs__cti[];
extern size_t es__chardefs__cti_size;
extern uint8_t Es__Es__G0__utb[];
extern size_t Es__Es__G0__utb_size;
extern uint8_t es__g1__ctb[];
extern size_t es__g1__ctb_size;
extern uint8_t es__g2__ctb[];
extern size_t es__g2__ctb_size;
extern uint8_t es__new__dis[];
extern size_t es__new__dis_size;
extern uint8_t es__old__dis[];
extern size_t es__old__dis_size;
extern uint8_t es__tbl[];
extern size_t es__tbl_size;
extern uint8_t et__g0__utb[];
extern size_t et__g0__utb_size;
extern uint8_t et__ctb[];
extern size_t et__ctb_size;
extern uint8_t et__tbl[];
extern size_t et__tbl_size;
extern uint8_t ethio__g1__ctb[];
extern size_t ethio__g1__ctb_size;
extern uint8_t eurodefs__cti[];
extern size_t eurodefs__cti_size;
extern uint8_t fa__ir__comp8__ctb[];
extern size_t fa__ir__comp8__ctb_size;
extern uint8_t fa__ir__g1__utb[];
extern size_t fa__ir__g1__utb_size;
extern uint8_t fi__fi__8dot__ctb[];
extern size_t fi__fi__8dot__ctb_size;
extern uint8_t fi__utb[];
extern size_t fi__utb_size;
extern uint8_t fr__bfu__comp6__utb[];
extern size_t fr__bfu__comp6__utb_size;
extern uint8_t fr__bfu__comp68__cti[];
extern size_t fr__bfu__comp68__cti_size;
extern uint8_t fr__bfu__comp8__utb[];
extern size_t fr__bfu__comp8__utb_size;
extern uint8_t fr__bfu__g2__ctb[];
extern size_t fr__bfu__g2__ctb_size;
extern uint8_t ga__g1__utb[];
extern size_t ga__g1__utb_size;
extern uint8_t ga__g2__ctb[];
extern size_t ga__g2__ctb_size;
extern uint8_t gd__ctb[];
extern size_t gd__ctb_size;
extern uint8_t gd__tbl[];
extern size_t gd__tbl_size;
extern uint8_t gez__tbl[];
extern size_t gez__tbl_size;
extern uint8_t gon__ctb[];
extern size_t gon__ctb_size;
extern uint8_t gon__tbl[];
extern size_t gon__tbl_size;
extern uint8_t gr__pl__comp8__uti[];
extern size_t gr__pl__comp8__uti_size;
extern uint8_t grc__international__common__uti[];
extern size_t grc__international__common__uti_size;
extern uint8_t grc__international__composed__uti[];
extern size_t grc__international__composed__uti_size;
extern uint8_t grc__international__decomposed__uti[];
extern size_t grc__international__decomposed__uti_size;
extern uint8_t grc__international__en__utb[];
extern size_t grc__international__en__utb_size;
extern uint8_t gu__in__g1__utb[];
extern size_t gu__in__g1__utb_size;
extern uint8_t gu__tbl[];
extern size_t gu__tbl_size;
extern uint8_t gujarati__cti[];
extern size_t gujarati__cti_size;
extern uint8_t gurumuki__cti[];
extern size_t gurumuki__cti_size;
extern uint8_t haw__us__g1__ctb[];
extern size_t haw__us__g1__ctb_size;
extern uint8_t he__IL__comp8__utb[];
extern size_t he__IL__comp8__utb_size;
extern uint8_t he__IL__utb[];
extern size_t he__IL__utb_size;
extern uint8_t hi__in__g1__utb[];
extern size_t hi__in__g1__utb_size;
extern uint8_t hi__tbl[];
extern size_t hi__tbl_size;
extern uint8_t hr__chardefs__cti[];
extern size_t hr__chardefs__cti_size;
extern uint8_t hr__comp8__tbl[];
extern size_t hr__comp8__tbl_size;
extern uint8_t hr__comp8__utb[];
extern size_t hr__comp8__utb_size;
extern uint8_t hr__digits__uti[];
extern size_t hr__digits__uti_size;
extern uint8_t hr__g1__ctb[];
extern size_t hr__g1__ctb_size;
extern uint8_t hr__g1__tbl[];
extern size_t hr__g1__tbl_size;
extern uint8_t hr__translation__cti[];
extern size_t hr__translation__cti_size;
extern uint8_t hu__backtranslate__correction__dis[];
extern size_t hu__backtranslate__correction__dis_size;
extern uint8_t hu__backtranslate__word__corrections__cti[];
extern size_t hu__backtranslate__word__corrections__cti_size;
extern uint8_t hu__chardefs__cti[];
extern size_t hu__chardefs__cti_size;
extern uint8_t hu__exceptionwords__cti[];
extern size_t hu__exceptionwords__cti_size;
extern uint8_t hu__hu__comp8__ctb[];
extern size_t hu__hu__comp8__ctb_size;
extern uint8_t hu__hu__g1__ctb[];
extern size_t hu__hu__g1__ctb_size;
extern uint8_t hu__hu__g1_braille_input__cti[];
extern size_t hu__hu__g1_braille_input__cti_size;
extern uint8_t hu__hu__g2__ctb[];
extern size_t hu__hu__g2__ctb_size;
extern uint8_t hu__hu__g2_exceptions__cti[];
extern size_t hu__hu__g2_exceptions__cti_size;
extern uint8_t hu__tbl[];
extern size_t hu__tbl_size;
extern uint8_t hy__ctb[];
extern size_t hy__ctb_size;
extern uint8_t hy__tbl[];
extern size_t hy__tbl_size;
extern uint8_t hyph_cs_CZ__dic[];
extern size_t hyph_cs_CZ__dic_size;
extern uint8_t hyph_da_DK__dic[];
extern size_t hyph_da_DK__dic_size;
extern uint8_t hyph_de_DE__dic[];
extern size_t hyph_de_DE__dic_size;
extern uint8_t hyph_en_US__dic[];
extern size_t hyph_en_US__dic_size;
extern uint8_t hyph_eo__dic[];
extern size_t hyph_eo__dic_size;
extern uint8_t hyph_es_ES__dic[];
extern size_t hyph_es_ES__dic_size;
extern uint8_t hyph_fr_FR__dic[];
extern size_t hyph_fr_FR__dic_size;
extern uint8_t hyph_hu_HU__dic[];
extern size_t hyph_hu_HU__dic_size;
extern uint8_t hyph_it_IT__dic[];
extern size_t hyph_it_IT__dic_size;
extern uint8_t hyph_nb_NO__dic[];
extern size_t hyph_nb_NO__dic_size;
extern uint8_t hyph_nl_NL__dic[];
extern size_t hyph_nl_NL__dic_size;
extern uint8_t hyph_nn_NO__dic[];
extern size_t hyph_nn_NO__dic_size;
extern uint8_t hyph_pl_PL__dic[];
extern size_t hyph_pl_PL__dic_size;
extern uint8_t hyph_pt_PT__dic[];
extern size_t hyph_pt_PT__dic_size;
extern uint8_t hyph_ru__dic[];
extern size_t hyph_ru__dic_size;
extern uint8_t hyph_sv_SE__dic[];
extern size_t hyph_sv_SE__dic_size;
extern uint8_t IPA__unicode__range__uti[];
extern size_t IPA__unicode__range__uti_size;
extern uint8_t IPA__utb[];
extern size_t IPA__utb_size;
extern uint8_t is__chardefs6__cti[];
extern size_t is__chardefs6__cti_size;
extern uint8_t is__chardefs8__cti[];
extern size_t is__chardefs8__cti_size;
extern uint8_t is__ctb[];
extern size_t is__ctb_size;
extern uint8_t is__tbl[];
extern size_t is__tbl_size;
extern uint8_t it__it__comp6__utb[];
extern size_t it__it__comp6__utb_size;
extern uint8_t it__it__comp8__utb[];
extern size_t it__it__comp8__utb_size;
extern uint8_t it__tbl[];
extern size_t it__tbl_size;
extern uint8_t iu__ca__g1__ctb[];
extern size_t iu__ca__g1__ctb_size;
extern uint8_t ja__kantenji__utb[];
extern size_t ja__kantenji__utb_size;
extern uint8_t ka__in__g1__utb[];
extern size_t ka__in__g1__utb_size;
extern uint8_t ka__utb[];
extern size_t ka__utb_size;
extern uint8_t kannada__cti[];
extern size_t kannada__cti_size;
extern uint8_t kh__in__g1__utb[];
extern size_t kh__in__g1__utb_size;
extern uint8_t kha__tbl[];
extern size_t kha__tbl_size;
extern uint8_t kk__utb[];
extern size_t kk__utb_size;
extern uint8_t km__g1__utb[];
extern size_t km__g1__utb_size;
extern uint8_t kmr__tbl[];
extern size_t kmr__tbl_size;
extern uint8_t kn__tbl[];
extern size_t kn__tbl_size;
extern uint8_t ko__2006__g1__ctb[];
extern size_t ko__2006__g1__ctb_size;
extern uint8_t ko__2006__g2__ctb[];
extern size_t ko__2006__g2__ctb_size;
extern uint8_t ko__2006__cti[];
extern size_t ko__2006__cti_size;
extern uint8_t ko__chars__cti[];
extern size_t ko__chars__cti_size;
extern uint8_t ko__g1__rules__cti[];
extern size_t ko__g1__rules__cti_size;
extern uint8_t ko__g1__ctb[];
extern size_t ko__g1__ctb_size;
extern uint8_t ko__g2__rules__cti[];
extern size_t ko__g2__rules__cti_size;
extern uint8_t ko__g2__ctb[];
extern size_t ko__g2__ctb_size;
extern uint8_t ko__cti[];
extern size_t ko__cti_size;
extern uint8_t kok__ctb[];
extern size_t kok__ctb_size;
extern uint8_t kok__tbl[];
extern size_t kok__tbl_size;
extern uint8_t kru__ctb[];
extern size_t kru__ctb_size;
extern uint8_t kru__tbl[];
extern size_t kru__tbl_size;
extern uint8_t ks__in__g1__utb[];
extern size_t ks__in__g1__utb_size;
extern uint8_t latinLetterDef6Dots__uti[];
extern size_t latinLetterDef6Dots__uti_size;
extern uint8_t latinLetterDef8Dots__uti[];
extern size_t latinLetterDef8Dots__uti_size;
extern uint8_t latinLowercase__uti[];
extern size_t latinLowercase__uti_size;
extern uint8_t latinUppercaseComp6__uti[];
extern size_t latinUppercaseComp6__uti_size;
extern uint8_t lg__ug__g1__utb[];
extern size_t lg__ug__g1__utb_size;
extern uint8_t litdigits6Dots__uti[];
extern size_t litdigits6Dots__uti_size;
extern uint8_t litdigits6DotsPlusDot6__uti[];
extern size_t litdigits6DotsPlusDot6__uti_size;
extern uint8_t loweredDigits6Dots__uti[];
extern size_t loweredDigits6Dots__uti_size;
extern uint8_t loweredDigits8Dots__uti[];
extern size_t loweredDigits8Dots__uti_size;
extern uint8_t lt__6dot__tbl[];
extern size_t lt__6dot__tbl_size;
extern uint8_t lt__6dot__utb[];
extern size_t lt__6dot__utb_size;
extern uint8_t lt__ctb[];
extern size_t lt__ctb_size;
extern uint8_t lt__tbl[];
extern size_t lt__tbl_size;
extern uint8_t Lv__Lv__g1__utb[];
extern size_t Lv__Lv__g1__utb_size;
extern uint8_t lv__tbl[];
extern size_t lv__tbl_size;
extern uint8_t Makefile__am[];
extern size_t Makefile__am_size;
extern uint8_t Makefile__in[];
extern size_t Makefile__in_size;
extern uint8_t maketablelist__sh[];
extern size_t maketablelist__sh_size;
extern uint8_t malayalam__cti[];
extern size_t malayalam__cti_size;
extern uint8_t mao__nz__g1__ctb[];
extern size_t mao__nz__g1__ctb_size;
extern uint8_t marburg_single_cell_defs__cti[];
extern size_t marburg_single_cell_defs__cti_size;
extern uint8_t marburg_unicode_defs__cti[];
extern size_t marburg_unicode_defs__cti_size;
extern uint8_t ml__in__g1__utb[];
extern size_t ml__in__g1__utb_size;
extern uint8_t ml__tbl[];
extern size_t ml__tbl_size;
extern uint8_t mn__in__g1__utb[];
extern size_t mn__in__g1__utb_size;
extern uint8_t mn__MN__common__cti[];
extern size_t mn__MN__common__cti_size;
extern uint8_t mn__MN__g1__utb[];
extern size_t mn__MN__g1__utb_size;
extern uint8_t mn__MN__g2__ctb[];
extern size_t mn__MN__g2__ctb_size;
extern uint8_t mni__tbl[];
extern size_t mni__tbl_size;
extern uint8_t mr__in__g1__utb[];
extern size_t mr__in__g1__utb_size;
extern uint8_t mr__tbl[];
extern size_t mr__tbl_size;
extern uint8_t ms__my__g2__ctb[];
extern size_t ms__my__g2__ctb_size;
extern uint8_t mt__ctb[];
extern size_t mt__ctb_size;
extern uint8_t mt__tbl[];
extern size_t mt__tbl_size;
extern uint8_t mun__ctb[];
extern size_t mun__ctb_size;
extern uint8_t mun__tbl[];
extern size_t mun__tbl_size;
extern uint8_t mwr__ctb[];
extern size_t mwr__ctb_size;
extern uint8_t mwr__tbl[];
extern size_t mwr__tbl_size;
extern uint8_t my__g1__utb[];
extern size_t my__g1__utb_size;
extern uint8_t my__g2__ctb[];
extern size_t my__g2__ctb_size;
extern uint8_t ne__ctb[];
extern size_t ne__ctb_size;
extern uint8_t ne__tbl[];
extern size_t ne__tbl_size;
extern uint8_t nemethdefs__cti[];
extern size_t nemethdefs__cti_size;
extern uint8_t nl__BE__dis[];
extern size_t nl__BE__dis_size;
extern uint8_t nl__chardefs__uti[];
extern size_t nl__chardefs__uti_size;
extern uint8_t nl__comp8__utb[];
extern size_t nl__comp8__utb_size;
extern uint8_t nl__NL__g0__utb[];
extern size_t nl__NL__g0__utb_size;
extern uint8_t nl__tbl[];
extern size_t nl__tbl_size;
extern uint8_t no__no__8dot__fallback__6dot__g0__utb[];
extern size_t no__no__8dot__fallback__6dot__g0__utb_size;
extern uint8_t no__no__8dot__utb[];
extern size_t no__no__8dot__utb_size;
extern uint8_t no__no__braillo__047__01__dis[];
extern size_t no__no__braillo__047__01__dis_size;
extern uint8_t no__no__chardefs6__uti[];
extern size_t no__no__chardefs6__uti_size;
extern uint8_t no__no__comp8__ctb[];
extern size_t no__no__comp8__ctb_size;
extern uint8_t no__no__g0__utb[];
extern size_t no__no__g0__utb_size;
extern uint8_t no__no__g1__ctb[];
extern size_t no__no__g1__ctb_size;
extern uint8_t no__no__g2__ctb[];
extern size_t no__no__g2__ctb_size;
extern uint8_t no__no__g3__ctb[];
extern size_t no__no__g3__ctb_size;
extern uint8_t no__no__generic__ctb[];
extern size_t no__no__generic__ctb_size;
extern uint8_t no__no__generic__dis[];
extern size_t no__no__generic__dis_size;
extern uint8_t no__no__latinLetterDef6Dots_diacritics__uti[];
extern size_t no__no__latinLetterDef6Dots_diacritics__uti_size;
extern uint8_t no__no__dis[];
extern size_t no__no__dis_size;
extern uint8_t np__in__g1__utb[];
extern size_t np__in__g1__utb_size;
extern uint8_t nso__za__g1__utb[];
extern size_t nso__za__g1__utb_size;
extern uint8_t nso__za__g2__ctb[];
extern size_t nso__za__g2__ctb_size;
extern uint8_t ny__mw__utb[];
extern size_t ny__mw__utb_size;
extern uint8_t or__in__g1__utb[];
extern size_t or__in__g1__utb_size;
extern uint8_t or__tbl[];
extern size_t or__tbl_size;
extern uint8_t oriya__cti[];
extern size_t oriya__cti_size;
extern uint8_t pa__tbl[];
extern size_t pa__tbl_size;
extern uint8_t pi__ctb[];
extern size_t pi__ctb_size;
extern uint8_t pi__tbl[];
extern size_t pi__tbl_size;
extern uint8_t pl__pl__comp8__ctb[];
extern size_t pl__pl__comp8__ctb_size;
extern uint8_t Pl__Pl__g1__utb[];
extern size_t Pl__Pl__g1__utb_size;
extern uint8_t pl__tbl[];
extern size_t pl__tbl_size;
extern uint8_t printables__cti[];
extern size_t printables__cti_size;
extern uint8_t pt__pt__comp8__ctb[];
extern size_t pt__pt__comp8__ctb_size;
extern uint8_t pt__pt__g1__utb[];
extern size_t pt__pt__g1__utb_size;
extern uint8_t pt__pt__g2__ctb[];
extern size_t pt__pt__g2__ctb_size;
extern uint8_t pt__tbl[];
extern size_t pt__tbl_size;
extern uint8_t pu__in__g1__utb[];
extern size_t pu__in__g1__utb_size;
extern uint8_t ro__ctb[];
extern size_t ro__ctb_size;
extern uint8_t ro__tbl[];
extern size_t ro__tbl_size;
extern uint8_t ru__brf__dis[];
extern size_t ru__brf__dis_size;
extern uint8_t ru__compbrl__ctb[];
extern size_t ru__compbrl__ctb_size;
extern uint8_t ru__letters__dis[];
extern size_t ru__letters__dis_size;
extern uint8_t ru__litbrl__detailed__utb[];
extern size_t ru__litbrl__detailed__utb_size;
extern uint8_t ru__litbrl__ctb[];
extern size_t ru__litbrl__ctb_size;
extern uint8_t ru__ru__g1__ctb[];
extern size_t ru__ru__g1__ctb_size;
extern uint8_t ru__unicode__dis[];
extern size_t ru__unicode__dis_size;
extern uint8_t ru__ctb[];
extern size_t ru__ctb_size;
extern uint8_t rw__rw__g1__utb[];
extern size_t rw__rw__g1__utb_size;
extern uint8_t sa__in__g1__utb[];
extern size_t sa__in__g1__utb_size;
extern uint8_t sa__tbl[];
extern size_t sa__tbl_size;
extern uint8_t sah__utb[];
extern size_t sah__utb_size;
extern uint8_t sd__tbl[];
extern size_t sd__tbl_size;
extern uint8_t se__se__ctb[];
extern size_t se__se__ctb_size;
extern uint8_t se__se__dis[];
extern size_t se__se__dis_size;
extern uint8_t si__in__g1__utb[];
extern size_t si__in__g1__utb_size;
extern uint8_t sin__cti[];
extern size_t sin__cti_size;
extern uint8_t sin__utb[];
extern size_t sin__utb_size;
extern uint8_t sk__g1__ctb[];
extern size_t sk__g1__ctb_size;
extern uint8_t sk__sk__g1__utb[];
extern size_t sk__sk__g1__utb_size;
extern uint8_t sk__sk__utb[];
extern size_t sk__sk__utb_size;
extern uint8_t sl__si__comp8__ctb[];
extern size_t sl__si__comp8__ctb_size;
extern uint8_t sl__si__g1__utb[];
extern size_t sl__si__g1__utb_size;
extern uint8_t sl__tbl[];
extern size_t sl__tbl_size;
extern uint8_t sot__za__g1__ctb[];
extern size_t sot__za__g1__ctb_size;
extern uint8_t sot__za__g2__ctb[];
extern size_t sot__za__g2__ctb_size;
extern uint8_t spaces__uti[];
extern size_t spaces__uti_size;
extern uint8_t sr__chardefs__cti[];
extern size_t sr__chardefs__cti_size;
extern uint8_t sr__g1__ctb[];
extern size_t sr__g1__ctb_size;
extern uint8_t sr__tbl[];
extern size_t sr__tbl_size;
extern uint8_t sv__1989__ctb[];
extern size_t sv__1989__ctb_size;
extern uint8_t sv__1996__ctb[];
extern size_t sv__1996__ctb_size;
extern uint8_t sv__g0__utb[];
extern size_t sv__g0__utb_size;
extern uint8_t sv__g1__ctb[];
extern size_t sv__g1__ctb_size;
extern uint8_t sv__g2__ctb[];
extern size_t sv__g2__ctb_size;
extern uint8_t sw__ke__g1__2__ctb[];
extern size_t sw__ke__g1__2__ctb_size;
extern uint8_t sw__ke__g1__3__ctb[];
extern size_t sw__ke__g1__3__ctb_size;
extern uint8_t sw__ke__g1__4__ctb[];
extern size_t sw__ke__g1__4__ctb_size;
extern uint8_t sw__ke__g1__5__ctb[];
extern size_t sw__ke__g1__5__ctb_size;
extern uint8_t sw__ke__g1__utb[];
extern size_t sw__ke__g1__utb_size;
extern uint8_t sw__ke__g2__ctb[];
extern size_t sw__ke__g2__ctb_size;
extern uint8_t ta__ta__g1__ctb[];
extern size_t ta__ta__g1__ctb_size;
extern uint8_t ta__ctb[];
extern size_t ta__ctb_size;
extern uint8_t ta__tbl[];
extern size_t ta__tbl_size;
extern uint8_t tamil__cti[];
extern size_t tamil__cti_size;
extern uint8_t te__in__g1__utb[];
extern size_t te__in__g1__utb_size;
extern uint8_t te__tbl[];
extern size_t te__tbl_size;
extern uint8_t telugu__cti[];
extern size_t telugu__cti_size;
extern uint8_t text_nabcc__dis[];
extern size_t text_nabcc__dis_size;
extern uint8_t tr__g1__ctb[];
extern size_t tr__g1__ctb_size;
extern uint8_t tr__g2__ctb[];
extern size_t tr__g2__ctb_size;
extern uint8_t tr__g2__tbl[];
extern size_t tr__g2__tbl_size;
extern uint8_t tr__ctb[];
extern size_t tr__ctb_size;
extern uint8_t tr__tbl[];
extern size_t tr__tbl_size;
extern uint8_t tsn__za__g1__ctb[];
extern size_t tsn__za__g1__ctb_size;
extern uint8_t tsn__za__g2__ctb[];
extern size_t tsn__za__g2__ctb_size;
extern uint8_t tt__utb[];
extern size_t tt__utb_size;
extern uint8_t uk__comp__utb[];
extern size_t uk__comp__utb_size;
extern uint8_t uk__utb[];
extern size_t uk__utb_size;
extern uint8_t ukchardefs__cti[];
extern size_t ukchardefs__cti_size;
extern uint8_t ukmaths_single_cell_defs__cti[];
extern size_t ukmaths_single_cell_defs__cti_size;
extern uint8_t ukmaths_unicode_defs__cti[];
extern size_t ukmaths_unicode_defs__cti_size;
extern uint8_t uni__text__dis[];
extern size_t uni__text__dis_size;
extern uint8_t unicode__braille__utb[];
extern size_t unicode__braille__utb_size;
extern uint8_t unicode__without__blank__dis[];
extern size_t unicode__without__blank__dis_size;
extern uint8_t unicode__dis[];
extern size_t unicode__dis_size;
extern uint8_t ur__pk__g1__utb[];
extern size_t ur__pk__g1__utb_size;
extern uint8_t ur__pk__g2__ctb[];
extern size_t ur__pk__g2__ctb_size;
extern uint8_t us__table__dis[];
extern size_t us__table__dis_size;
extern uint8_t uz__g1__utb[];
extern size_t uz__g1__utb_size;
extern uint8_t ve__za__g1__utb[];
extern size_t ve__za__g1__utb_size;
extern uint8_t ve__za__g2__ctb[];
extern size_t ve__za__g2__ctb_size;
extern uint8_t vi__cb8__utb[];
extern size_t vi__cb8__utb_size;
extern uint8_t vi__charsdef__uti[];
extern size_t vi__charsdef__uti_size;
extern uint8_t vi__lettersdef__uti[];
extern size_t vi__lettersdef__uti_size;
extern uint8_t vi__puncsdef__uti[];
extern size_t vi__puncsdef__uti_size;
extern uint8_t vi__saigon__g1__ctb[];
extern size_t vi__saigon__g1__ctb_size;
extern uint8_t vi__vn__g0__utb[];
extern size_t vi__vn__g0__utb_size;
extern uint8_t vi__vn__g1__ctb[];
extern size_t vi__vn__g1__ctb_size;
extern uint8_t vi__vn__g2__ctb[];
extern size_t vi__vn__g2__ctb_size;
extern uint8_t wiskunde__chardefs__cti[];
extern size_t wiskunde__chardefs__cti_size;
extern uint8_t wordcx__dis[];
extern size_t wordcx__dis_size;
extern uint8_t xh__za__g1__utb[];
extern size_t xh__za__g1__utb_size;
extern uint8_t xh__za__g2__ctb[];
extern size_t xh__za__g2__ctb_size;
extern uint8_t zh__chn__ctb[];
extern size_t zh__chn__ctb_size;
extern uint8_t zh__hk__ctb[];
extern size_t zh__hk__ctb_size;
extern uint8_t zh__tw__ctb[];
extern size_t zh__tw__ctb_size;
extern uint8_t zh_CHN__tbl[];
extern size_t zh_CHN__tbl_size;
extern uint8_t zh_HK__tbl[];
extern size_t zh_HK__tbl_size;
extern uint8_t zhcn__cbs__ctb[];
extern size_t zhcn__cbs__ctb_size;
extern uint8_t zhcn__g1__ctb[];
extern size_t zhcn__g1__ctb_size;
extern uint8_t zhcn__g2__ctb[];
extern size_t zhcn__g2__ctb_size;
extern uint8_t zu__za__g1__utb[];
extern size_t zu__za__g1__utb_size;
extern uint8_t zu__za__g2__ctb[];
extern size_t zu__za__g2__ctb_size;
lou_dbfile lou_database[] = {
	{ "afr-za-g1.ctb",afr__za__g1__ctb, &afr__za__g1__ctb_size },
	{ "afr-za-g2.ctb",afr__za__g2__ctb, &afr__za__g2__ctb_size },
	{ "ar-ar-comp8.utb",ar__ar__comp8__utb, &ar__ar__comp8__utb_size },
	{ "ar-ar-g1-core.uti",ar__ar__g1__core__uti, &ar__ar__g1__core__uti_size },
	{ "ar-ar-g1.utb",ar__ar__g1__utb, &ar__ar__g1__utb_size },
	{ "ar-ar-g2.ctb",ar__ar__g2__ctb, &ar__ar__g2__ctb_size },
	{ "ar-ar-math.uti",ar__ar__math__uti, &ar__ar__math__uti_size },
	{ "ar.tbl",ar__tbl, &ar__tbl_size },
	{ "as-in-g1.utb",as__in__g1__utb, &as__in__g1__utb_size },
	{ "as.tbl",as__tbl, &as__tbl_size },
	{ "aw-in-g1.utb",aw__in__g1__utb, &aw__in__g1__utb_size },
	{ "awa.tbl",awa__tbl, &awa__tbl_size },
	{ "ba.utb",ba__utb, &ba__utb_size },
	{ "be-in-g1.utb",be__in__g1__utb, &be__in__g1__utb_size },
	{ "bel-comp.utb",bel__comp__utb, &bel__comp__utb_size },
	{ "bel.utb",bel__utb, &bel__utb_size },
	{ "bengali.cti",bengali__cti, &bengali__cti_size },
	{ "bg.ctb",bg__ctb, &bg__ctb_size },
	{ "bg.dis",bg__dis, &bg__dis_size },
	{ "bg.tbl",bg__tbl, &bg__tbl_size },
	{ "bg.utb",bg__utb, &bg__utb_size },
	{ "bh.ctb",bh__ctb, &bh__ctb_size },
	{ "bh.tbl",bh__tbl, &bh__tbl_size },
	{ "bn.tbl",bn__tbl, &bn__tbl_size },
	{ "bo.ctb",bo__ctb, &bo__ctb_size },
	{ "bo.tbl",bo__tbl, &bo__tbl_size },
	{ "boxes.ctb",boxes__ctb, &boxes__ctb_size },
	{ "br-in-g1.utb",br__in__g1__utb, &br__in__g1__utb_size },
	{ "bra.tbl",bra__tbl, &bra__tbl_size },
	{ "braille-patterns.cti",braille__patterns__cti, &braille__patterns__cti_size },
	{ "ca-chardefs.cti",ca__chardefs__cti, &ca__chardefs__cti_size },
	{ "ca-g1.ctb",ca__g1__ctb, &ca__g1__ctb_size },
	{ "ca.tbl",ca__tbl, &ca__tbl_size },
	{ "chr-us-g1.ctb",chr__us__g1__ctb, &chr__us__g1__ctb_size },
	{ "ckb-chardefs.cti",ckb__chardefs__cti, &ckb__chardefs__cti_size },
	{ "ckb-g1.ctb",ckb__g1__ctb, &ckb__g1__ctb_size },
	{ "ckb-translation.cti",ckb__translation__cti, &ckb__translation__cti_size },
	{ "ckb.tbl",ckb__tbl, &ckb__tbl_size },
	{ "compress.cti",compress__cti, &compress__cti_size },
	{ "controlchars.cti",controlchars__cti, &controlchars__cti_size },
	{ "cop-eg-comp8.utb",cop__eg__comp8__utb, &cop__eg__comp8__utb_size },
	{ "corrections.cti",corrections__cti, &corrections__cti_size },
	{ "countries.cti",countries__cti, &countries__cti_size },
	{ "cs-chardefs.cti",cs__chardefs__cti, &cs__chardefs__cti_size },
	{ "cs-comp8.utb",cs__comp8__utb, &cs__comp8__utb_size },
	{ "cs-g1.ctb",cs__g1__ctb, &cs__g1__ctb_size },
	{ "cs-translation.cti",cs__translation__cti, &cs__translation__cti_size },
	{ "cs.tbl",cs__tbl, &cs__tbl_size },
	{ "cy-cy-g1.utb",cy__cy__g1__utb, &cy__cy__g1__utb_size },
	{ "cy-cy-g2.ctb",cy__cy__g2__ctb, &cy__cy__g2__ctb_size },
	{ "cy.tbl",cy__tbl, &cy__tbl_size },
	{ "da-dk-6miscChars.cti",da__dk__6miscChars__cti, &da__dk__6miscChars__cti_size },
	{ "da-dk-6miscChars_1993.cti",da__dk__6miscChars_1993__cti, &da__dk__6miscChars_1993__cti_size },
	{ "da-dk-8miscChars.cti",da__dk__8miscChars__cti, &da__dk__8miscChars__cti_size },
	{ "da-dk-8miscChars_1993.cti",da__dk__8miscChars_1993__cti, &da__dk__8miscChars_1993__cti_size },
	{ "da-dk-g08.ctb",da__dk__g08__ctb, &da__dk__g08__ctb_size },
	{ "da-dk-g08_1993.ctb",da__dk__g08_1993__ctb, &da__dk__g08_1993__ctb_size },
	{ "da-dk-g16-lit_1993.ctb",da__dk__g16__lit_1993__ctb, &da__dk__g16__lit_1993__ctb_size },
	{ "da-dk-g16.ctb",da__dk__g16__ctb, &da__dk__g16__ctb_size },
	{ "da-dk-g16_1993.ctb",da__dk__g16_1993__ctb, &da__dk__g16_1993__ctb_size },
	{ "da-dk-g18.ctb",da__dk__g18__ctb, &da__dk__g18__ctb_size },
	{ "da-dk-g18_1993.ctb",da__dk__g18_1993__ctb, &da__dk__g18_1993__ctb_size },
	{ "da-dk-g2.dic",da__dk__g2__dic, &da__dk__g2__dic_size },
	{ "da-dk-g26-lit_1993.ctb",da__dk__g26__lit_1993__ctb, &da__dk__g26__lit_1993__ctb_size },
	{ "da-dk-g26.ctb",da__dk__g26__ctb, &da__dk__g26__ctb_size },
	{ "da-dk-g26_1993.ctb",da__dk__g26_1993__ctb, &da__dk__g26_1993__ctb_size },
	{ "da-dk-g26l-lit_1993.ctb",da__dk__g26l__lit_1993__ctb, &da__dk__g26l__lit_1993__ctb_size },
	{ "da-dk-g26l_1993.ctb",da__dk__g26l_1993__ctb, &da__dk__g26l_1993__ctb_size },
	{ "da-dk-g28.ctb",da__dk__g28__ctb, &da__dk__g28__ctb_size },
	{ "da-dk-g28_1993.ctb",da__dk__g28_1993__ctb, &da__dk__g28_1993__ctb_size },
	{ "da-dk-g28l_1993.ctb",da__dk__g28l_1993__ctb, &da__dk__g28l_1993__ctb_size },
	{ "da-dk-g2_1993.dic",da__dk__g2_1993__dic, &da__dk__g2_1993__dic_size },
	{ "da-dk-octobraille.dis",da__dk__octobraille__dis, &da__dk__octobraille__dis_size },
	{ "da-dk-octobraille_1993.dis",da__dk__octobraille_1993__dis, &da__dk__octobraille_1993__dis_size },
	{ "de-accents-detailed.cti",de__accents__detailed__cti, &de__accents__detailed__cti_size },
	{ "de-accents.cti",de__accents__cti, &de__accents__cti_size },
	{ "de-chardefs6.cti",de__chardefs6__cti, &de__chardefs6__cti_size },
	{ "de-chardefs8.cti",de__chardefs8__cti, &de__chardefs8__cti_size },
	{ "de-chess.ctb",de__chess__ctb, &de__chess__ctb_size },
	{ "de-comp6.utb",de__comp6__utb, &de__comp6__utb_size },
	{ "de-de-comp8.ctb",de__de__comp8__ctb, &de__de__comp8__ctb_size },
	{ "de-de.dis",de__de__dis, &de__de__dis_size },
	{ "de-eurobrl6.dis",de__eurobrl6__dis, &de__eurobrl6__dis_size },
	{ "de-eurobrl6u.dis",de__eurobrl6u__dis, &de__eurobrl6u__dis_size },
	{ "de-g0-core.uti",de__g0__core__uti, &de__g0__core__uti_size },
	{ "de-g0-detailed.utb",de__g0__detailed__utb, &de__g0__detailed__utb_size },
	{ "de-g0.utb",de__g0__utb, &de__g0__utb_size },
	{ "de-g1-core-patterns.dic",de__g1__core__patterns__dic, &de__g1__core__patterns__dic_size },
	{ "de-g1-core.cti",de__g1__core__cti, &de__g1__core__cti_size },
	{ "de-g1-detailed.ctb",de__g1__detailed__ctb, &de__g1__detailed__ctb_size },
	{ "de-g1.ctb",de__g1__ctb, &de__g1__ctb_size },
	{ "de-g2-core-patterns.dic",de__g2__core__patterns__dic, &de__g2__core__patterns__dic_size },
	{ "de-g2-core.cti",de__g2__core__cti, &de__g2__core__cti_size },
	{ "de-g2-detailed.ctb",de__g2__detailed__ctb, &de__g2__detailed__ctb_size },
	{ "de-g2.ctb",de__g2__ctb, &de__g2__ctb_size },
	{ "devanagari.cti",devanagari__cti, &devanagari__cti_size },
	{ "digits6Dots.uti",digits6Dots__uti, &digits6Dots__uti_size },
	{ "digits6DotsPlusDot6.uti",digits6DotsPlusDot6__uti, &digits6DotsPlusDot6__uti_size },
	{ "digits8Dots.uti",digits8Dots__uti, &digits8Dots__uti_size },
	{ "dra.ctb",dra__ctb, &dra__ctb_size },
	{ "dra.tbl",dra__tbl, &dra__tbl_size },
	{ "el.ctb",el__ctb, &el__ctb_size },
	{ "en-chardefs.cti",en__chardefs__cti, &en__chardefs__cti_size },
	{ "en-chess.ctb",en__chess__ctb, &en__chess__ctb_size },
	{ "en-gb-comp8.ctb",en__gb__comp8__ctb, &en__gb__comp8__ctb_size },
	{ "en-gb-g1.utb",en__gb__g1__utb, &en__gb__g1__utb_size },
	{ "en-GB-g2.ctb",en__GB__g2__ctb, &en__GB__g2__ctb_size },
	{ "en-in-g1.ctb",en__in__g1__ctb, &en__in__g1__ctb_size },
	{ "en-nabcc.utb",en__nabcc__utb, &en__nabcc__utb_size },
	{ "en-ueb-chardefs.uti",en__ueb__chardefs__uti, &en__ueb__chardefs__uti_size },
	{ "en-ueb-g1.ctb",en__ueb__g1__ctb, &en__ueb__g1__ctb_size },
	{ "en-ueb-g2.ctb",en__ueb__g2__ctb, &en__ueb__g2__ctb_size },
	{ "en-ueb-math.ctb",en__ueb__math__ctb, &en__ueb__math__ctb_size },
	{ "en-us-brf.dis",en__us__brf__dis, &en__us__brf__dis_size },
	{ "en-us-comp6.ctb",en__us__comp6__ctb, &en__us__comp6__ctb_size },
	{ "en-us-comp8-ext.utb",en__us__comp8__ext__utb, &en__us__comp8__ext__utb_size },
	{ "en-us-comp8.ctb",en__us__comp8__ctb, &en__us__comp8__ctb_size },
	{ "en-us-compbrl.uti",en__us__compbrl__uti, &en__us__compbrl__uti_size },
	{ "en-us-emphasis.uti",en__us__emphasis__uti, &en__us__emphasis__uti_size },
	{ "en-us-g1.ctb",en__us__g1__ctb, &en__us__g1__ctb_size },
	{ "en-us-g2.ctb",en__us__g2__ctb, &en__us__g2__ctb_size },
	{ "en-us-interline.ctb",en__us__interline__ctb, &en__us__interline__ctb_size },
	{ "en-us-mathtext.ctb",en__us__mathtext__ctb, &en__us__mathtext__ctb_size },
	{ "en_CA.ctb",en_CA__ctb, &en_CA__ctb_size },
	{ "en_CA.tbl",en_CA__tbl, &en_CA__tbl_size },
	{ "en_GB.tbl",en_GB__tbl, &en_GB__tbl_size },
	{ "en_US-comp8-ext.tbl",en_US__comp8__ext__tbl, &en_US__comp8__ext__tbl_size },
	{ "en_US.tbl",en_US__tbl, &en_US__tbl_size },
	{ "eo-g1-x-system.ctb",eo__g1__x__system__ctb, &eo__g1__x__system__ctb_size },
	{ "eo-g1.ctb",eo__g1__ctb, &eo__g1__ctb_size },
	{ "eo.tbl",eo__tbl, &eo__tbl_size },
	{ "es-chardefs.cti",es__chardefs__cti, &es__chardefs__cti_size },
	{ "Es-Es-G0.utb",Es__Es__G0__utb, &Es__Es__G0__utb_size },
	{ "es-g1.ctb",es__g1__ctb, &es__g1__ctb_size },
	{ "es-g2.ctb",es__g2__ctb, &es__g2__ctb_size },
	{ "es-new.dis",es__new__dis, &es__new__dis_size },
	{ "es-old.dis",es__old__dis, &es__old__dis_size },
	{ "es.tbl",es__tbl, &es__tbl_size },
	{ "et-g0.utb",et__g0__utb, &et__g0__utb_size },
	{ "et.ctb",et__ctb, &et__ctb_size },
	{ "et.tbl",et__tbl, &et__tbl_size },
	{ "ethio-g1.ctb",ethio__g1__ctb, &ethio__g1__ctb_size },
	{ "eurodefs.cti",eurodefs__cti, &eurodefs__cti_size },
	{ "fa-ir-comp8.ctb",fa__ir__comp8__ctb, &fa__ir__comp8__ctb_size },
	{ "fa-ir-g1.utb",fa__ir__g1__utb, &fa__ir__g1__utb_size },
	{ "fi-fi-8dot.ctb",fi__fi__8dot__ctb, &fi__fi__8dot__ctb_size },
	{ "fi.utb",fi__utb, &fi__utb_size },
	{ "fr-bfu-comp6.utb",fr__bfu__comp6__utb, &fr__bfu__comp6__utb_size },
	{ "fr-bfu-comp68.cti",fr__bfu__comp68__cti, &fr__bfu__comp68__cti_size },
	{ "fr-bfu-comp8.utb",fr__bfu__comp8__utb, &fr__bfu__comp8__utb_size },
	{ "fr-bfu-g2.ctb",fr__bfu__g2__ctb, &fr__bfu__g2__ctb_size },
	{ "ga-g1.utb",ga__g1__utb, &ga__g1__utb_size },
	{ "ga-g2.ctb",ga__g2__ctb, &ga__g2__ctb_size },
	{ "gd.ctb",gd__ctb, &gd__ctb_size },
	{ "gd.tbl",gd__tbl, &gd__tbl_size },
	{ "gez.tbl",gez__tbl, &gez__tbl_size },
	{ "gon.ctb",gon__ctb, &gon__ctb_size },
	{ "gon.tbl",gon__tbl, &gon__tbl_size },
	{ "gr-pl-comp8.uti",gr__pl__comp8__uti, &gr__pl__comp8__uti_size },
	{ "grc-international-common.uti",grc__international__common__uti, &grc__international__common__uti_size },
	{ "grc-international-composed.uti",grc__international__composed__uti, &grc__international__composed__uti_size },
	{ "grc-international-decomposed.uti",grc__international__decomposed__uti, &grc__international__decomposed__uti_size },
	{ "grc-international-en.utb",grc__international__en__utb, &grc__international__en__utb_size },
	{ "gu-in-g1.utb",gu__in__g1__utb, &gu__in__g1__utb_size },
	{ "gu.tbl",gu__tbl, &gu__tbl_size },
	{ "gujarati.cti",gujarati__cti, &gujarati__cti_size },
	{ "gurumuki.cti",gurumuki__cti, &gurumuki__cti_size },
	{ "haw-us-g1.ctb",haw__us__g1__ctb, &haw__us__g1__ctb_size },
	{ "he-IL-comp8.utb",he__IL__comp8__utb, &he__IL__comp8__utb_size },
	{ "he-IL.utb",he__IL__utb, &he__IL__utb_size },
	{ "hi-in-g1.utb",hi__in__g1__utb, &hi__in__g1__utb_size },
	{ "hi.tbl",hi__tbl, &hi__tbl_size },
	{ "hr-chardefs.cti",hr__chardefs__cti, &hr__chardefs__cti_size },
	{ "hr-comp8.tbl",hr__comp8__tbl, &hr__comp8__tbl_size },
	{ "hr-comp8.utb",hr__comp8__utb, &hr__comp8__utb_size },
	{ "hr-digits.uti",hr__digits__uti, &hr__digits__uti_size },
	{ "hr-g1.ctb",hr__g1__ctb, &hr__g1__ctb_size },
	{ "hr-g1.tbl",hr__g1__tbl, &hr__g1__tbl_size },
	{ "hr-translation.cti",hr__translation__cti, &hr__translation__cti_size },
	{ "hu-backtranslate-correction.dis",hu__backtranslate__correction__dis, &hu__backtranslate__correction__dis_size },
	{ "hu-backtranslate-word-corrections.cti",hu__backtranslate__word__corrections__cti, &hu__backtranslate__word__corrections__cti_size },
	{ "hu-chardefs.cti",hu__chardefs__cti, &hu__chardefs__cti_size },
	{ "hu-exceptionwords.cti",hu__exceptionwords__cti, &hu__exceptionwords__cti_size },
	{ "hu-hu-comp8.ctb",hu__hu__comp8__ctb, &hu__hu__comp8__ctb_size },
	{ "hu-hu-g1.ctb",hu__hu__g1__ctb, &hu__hu__g1__ctb_size },
	{ "hu-hu-g1_braille_input.cti",hu__hu__g1_braille_input__cti, &hu__hu__g1_braille_input__cti_size },
	{ "hu-hu-g2.ctb",hu__hu__g2__ctb, &hu__hu__g2__ctb_size },
	{ "hu-hu-g2_exceptions.cti",hu__hu__g2_exceptions__cti, &hu__hu__g2_exceptions__cti_size },
	{ "hu.tbl",hu__tbl, &hu__tbl_size },
	{ "hy.ctb",hy__ctb, &hy__ctb_size },
	{ "hy.tbl",hy__tbl, &hy__tbl_size },
	{ "hyph_cs_CZ.dic",hyph_cs_CZ__dic, &hyph_cs_CZ__dic_size },
	{ "hyph_da_DK.dic",hyph_da_DK__dic, &hyph_da_DK__dic_size },
	{ "hyph_de_DE.dic",hyph_de_DE__dic, &hyph_de_DE__dic_size },
	{ "hyph_en_US.dic",hyph_en_US__dic, &hyph_en_US__dic_size },
	{ "hyph_eo.dic",hyph_eo__dic, &hyph_eo__dic_size },
	{ "hyph_es_ES.dic",hyph_es_ES__dic, &hyph_es_ES__dic_size },
	{ "hyph_fr_FR.dic",hyph_fr_FR__dic, &hyph_fr_FR__dic_size },
	{ "hyph_hu_HU.dic",hyph_hu_HU__dic, &hyph_hu_HU__dic_size },
	{ "hyph_it_IT.dic",hyph_it_IT__dic, &hyph_it_IT__dic_size },
	{ "hyph_nb_NO.dic",hyph_nb_NO__dic, &hyph_nb_NO__dic_size },
	{ "hyph_nl_NL.dic",hyph_nl_NL__dic, &hyph_nl_NL__dic_size },
	{ "hyph_nn_NO.dic",hyph_nn_NO__dic, &hyph_nn_NO__dic_size },
	{ "hyph_pl_PL.dic",hyph_pl_PL__dic, &hyph_pl_PL__dic_size },
	{ "hyph_pt_PT.dic",hyph_pt_PT__dic, &hyph_pt_PT__dic_size },
	{ "hyph_ru.dic",hyph_ru__dic, &hyph_ru__dic_size },
	{ "hyph_sv_SE.dic",hyph_sv_SE__dic, &hyph_sv_SE__dic_size },
	{ "IPA-unicode-range.uti",IPA__unicode__range__uti, &IPA__unicode__range__uti_size },
	{ "IPA.utb",IPA__utb, &IPA__utb_size },
	{ "is-chardefs6.cti",is__chardefs6__cti, &is__chardefs6__cti_size },
	{ "is-chardefs8.cti",is__chardefs8__cti, &is__chardefs8__cti_size },
	{ "is.ctb",is__ctb, &is__ctb_size },
	{ "is.tbl",is__tbl, &is__tbl_size },
	{ "it-it-comp6.utb",it__it__comp6__utb, &it__it__comp6__utb_size },
	{ "it-it-comp8.utb",it__it__comp8__utb, &it__it__comp8__utb_size },
	{ "it.tbl",it__tbl, &it__tbl_size },
	{ "iu-ca-g1.ctb",iu__ca__g1__ctb, &iu__ca__g1__ctb_size },
	{ "ja-kantenji.utb",ja__kantenji__utb, &ja__kantenji__utb_size },
	{ "ka-in-g1.utb",ka__in__g1__utb, &ka__in__g1__utb_size },
	{ "ka.utb",ka__utb, &ka__utb_size },
	{ "kannada.cti",kannada__cti, &kannada__cti_size },
	{ "kh-in-g1.utb",kh__in__g1__utb, &kh__in__g1__utb_size },
	{ "kha.tbl",kha__tbl, &kha__tbl_size },
	{ "kk.utb",kk__utb, &kk__utb_size },
	{ "km-g1.utb",km__g1__utb, &km__g1__utb_size },
	{ "kmr.tbl",kmr__tbl, &kmr__tbl_size },
	{ "kn.tbl",kn__tbl, &kn__tbl_size },
	{ "ko-2006-g1.ctb",ko__2006__g1__ctb, &ko__2006__g1__ctb_size },
	{ "ko-2006-g2.ctb",ko__2006__g2__ctb, &ko__2006__g2__ctb_size },
	{ "ko-2006.cti",ko__2006__cti, &ko__2006__cti_size },
	{ "ko-chars.cti",ko__chars__cti, &ko__chars__cti_size },
	{ "ko-g1-rules.cti",ko__g1__rules__cti, &ko__g1__rules__cti_size },
	{ "ko-g1.ctb",ko__g1__ctb, &ko__g1__ctb_size },
	{ "ko-g2-rules.cti",ko__g2__rules__cti, &ko__g2__rules__cti_size },
	{ "ko-g2.ctb",ko__g2__ctb, &ko__g2__ctb_size },
	{ "ko.cti",ko__cti, &ko__cti_size },
	{ "kok.ctb",kok__ctb, &kok__ctb_size },
	{ "kok.tbl",kok__tbl, &kok__tbl_size },
	{ "kru.ctb",kru__ctb, &kru__ctb_size },
	{ "kru.tbl",kru__tbl, &kru__tbl_size },
	{ "ks-in-g1.utb",ks__in__g1__utb, &ks__in__g1__utb_size },
	{ "latinLetterDef6Dots.uti",latinLetterDef6Dots__uti, &latinLetterDef6Dots__uti_size },
	{ "latinLetterDef8Dots.uti",latinLetterDef8Dots__uti, &latinLetterDef8Dots__uti_size },
	{ "latinLowercase.uti",latinLowercase__uti, &latinLowercase__uti_size },
	{ "latinUppercaseComp6.uti",latinUppercaseComp6__uti, &latinUppercaseComp6__uti_size },
	{ "lg-ug-g1.utb",lg__ug__g1__utb, &lg__ug__g1__utb_size },
	{ "litdigits6Dots.uti",litdigits6Dots__uti, &litdigits6Dots__uti_size },
	{ "litdigits6DotsPlusDot6.uti",litdigits6DotsPlusDot6__uti, &litdigits6DotsPlusDot6__uti_size },
	{ "loweredDigits6Dots.uti",loweredDigits6Dots__uti, &loweredDigits6Dots__uti_size },
	{ "loweredDigits8Dots.uti",loweredDigits8Dots__uti, &loweredDigits8Dots__uti_size },
	{ "lt-6dot.tbl",lt__6dot__tbl, &lt__6dot__tbl_size },
	{ "lt-6dot.utb",lt__6dot__utb, &lt__6dot__utb_size },
	{ "lt.ctb",lt__ctb, &lt__ctb_size },
	{ "lt.tbl",lt__tbl, &lt__tbl_size },
	{ "Lv-Lv-g1.utb",Lv__Lv__g1__utb, &Lv__Lv__g1__utb_size },
	{ "lv.tbl",lv__tbl, &lv__tbl_size },
	{ "Makefile.am",Makefile__am, &Makefile__am_size },
	{ "Makefile.in",Makefile__in, &Makefile__in_size },
	{ "maketablelist.sh",maketablelist__sh, &maketablelist__sh_size },
	{ "malayalam.cti",malayalam__cti, &malayalam__cti_size },
	{ "mao-nz-g1.ctb",mao__nz__g1__ctb, &mao__nz__g1__ctb_size },
	{ "marburg_single_cell_defs.cti",marburg_single_cell_defs__cti, &marburg_single_cell_defs__cti_size },
	{ "marburg_unicode_defs.cti",marburg_unicode_defs__cti, &marburg_unicode_defs__cti_size },
	{ "ml-in-g1.utb",ml__in__g1__utb, &ml__in__g1__utb_size },
	{ "ml.tbl",ml__tbl, &ml__tbl_size },
	{ "mn-in-g1.utb",mn__in__g1__utb, &mn__in__g1__utb_size },
	{ "mn-MN-common.cti",mn__MN__common__cti, &mn__MN__common__cti_size },
	{ "mn-MN-g1.utb",mn__MN__g1__utb, &mn__MN__g1__utb_size },
	{ "mn-MN-g2.ctb",mn__MN__g2__ctb, &mn__MN__g2__ctb_size },
	{ "mni.tbl",mni__tbl, &mni__tbl_size },
	{ "mr-in-g1.utb",mr__in__g1__utb, &mr__in__g1__utb_size },
	{ "mr.tbl",mr__tbl, &mr__tbl_size },
	{ "ms-my-g2.ctb",ms__my__g2__ctb, &ms__my__g2__ctb_size },
	{ "mt.ctb",mt__ctb, &mt__ctb_size },
	{ "mt.tbl",mt__tbl, &mt__tbl_size },
	{ "mun.ctb",mun__ctb, &mun__ctb_size },
	{ "mun.tbl",mun__tbl, &mun__tbl_size },
	{ "mwr.ctb",mwr__ctb, &mwr__ctb_size },
	{ "mwr.tbl",mwr__tbl, &mwr__tbl_size },
	{ "my-g1.utb",my__g1__utb, &my__g1__utb_size },
	{ "my-g2.ctb",my__g2__ctb, &my__g2__ctb_size },
	{ "ne.ctb",ne__ctb, &ne__ctb_size },
	{ "ne.tbl",ne__tbl, &ne__tbl_size },
	{ "nemethdefs.cti",nemethdefs__cti, &nemethdefs__cti_size },
	{ "nl-BE.dis",nl__BE__dis, &nl__BE__dis_size },
	{ "nl-chardefs.uti",nl__chardefs__uti, &nl__chardefs__uti_size },
	{ "nl-comp8.utb",nl__comp8__utb, &nl__comp8__utb_size },
	{ "nl-NL-g0.utb",nl__NL__g0__utb, &nl__NL__g0__utb_size },
	{ "nl.tbl",nl__tbl, &nl__tbl_size },
	{ "no-no-8dot-fallback-6dot-g0.utb",no__no__8dot__fallback__6dot__g0__utb, &no__no__8dot__fallback__6dot__g0__utb_size },
	{ "no-no-8dot.utb",no__no__8dot__utb, &no__no__8dot__utb_size },
	{ "no-no-braillo-047-01.dis",no__no__braillo__047__01__dis, &no__no__braillo__047__01__dis_size },
	{ "no-no-chardefs6.uti",no__no__chardefs6__uti, &no__no__chardefs6__uti_size },
	{ "no-no-comp8.ctb",no__no__comp8__ctb, &no__no__comp8__ctb_size },
	{ "no-no-g0.utb",no__no__g0__utb, &no__no__g0__utb_size },
	{ "no-no-g1.ctb",no__no__g1__ctb, &no__no__g1__ctb_size },
	{ "no-no-g2.ctb",no__no__g2__ctb, &no__no__g2__ctb_size },
	{ "no-no-g3.ctb",no__no__g3__ctb, &no__no__g3__ctb_size },
	{ "no-no-generic.ctb",no__no__generic__ctb, &no__no__generic__ctb_size },
	{ "no-no-generic.dis",no__no__generic__dis, &no__no__generic__dis_size },
	{ "no-no-latinLetterDef6Dots_diacritics.uti",no__no__latinLetterDef6Dots_diacritics__uti, &no__no__latinLetterDef6Dots_diacritics__uti_size },
	{ "no-no.dis",no__no__dis, &no__no__dis_size },
	{ "np-in-g1.utb",np__in__g1__utb, &np__in__g1__utb_size },
	{ "nso-za-g1.utb",nso__za__g1__utb, &nso__za__g1__utb_size },
	{ "nso-za-g2.ctb",nso__za__g2__ctb, &nso__za__g2__ctb_size },
	{ "ny-mw.utb",ny__mw__utb, &ny__mw__utb_size },
	{ "or-in-g1.utb",or__in__g1__utb, &or__in__g1__utb_size },
	{ "or.tbl",or__tbl, &or__tbl_size },
	{ "oriya.cti",oriya__cti, &oriya__cti_size },
	{ "pa.tbl",pa__tbl, &pa__tbl_size },
	{ "pi.ctb",pi__ctb, &pi__ctb_size },
	{ "pi.tbl",pi__tbl, &pi__tbl_size },
	{ "pl-pl-comp8.ctb",pl__pl__comp8__ctb, &pl__pl__comp8__ctb_size },
	{ "Pl-Pl-g1.utb",Pl__Pl__g1__utb, &Pl__Pl__g1__utb_size },
	{ "pl.tbl",pl__tbl, &pl__tbl_size },
	{ "printables.cti",printables__cti, &printables__cti_size },
	{ "pt-pt-comp8.ctb",pt__pt__comp8__ctb, &pt__pt__comp8__ctb_size },
	{ "pt-pt-g1.utb",pt__pt__g1__utb, &pt__pt__g1__utb_size },
	{ "pt-pt-g2.ctb",pt__pt__g2__ctb, &pt__pt__g2__ctb_size },
	{ "pt.tbl",pt__tbl, &pt__tbl_size },
	{ "pu-in-g1.utb",pu__in__g1__utb, &pu__in__g1__utb_size },
	{ "ro.ctb",ro__ctb, &ro__ctb_size },
	{ "ro.tbl",ro__tbl, &ro__tbl_size },
	{ "ru-brf.dis",ru__brf__dis, &ru__brf__dis_size },
	{ "ru-compbrl.ctb",ru__compbrl__ctb, &ru__compbrl__ctb_size },
	{ "ru-letters.dis",ru__letters__dis, &ru__letters__dis_size },
	{ "ru-litbrl-detailed.utb",ru__litbrl__detailed__utb, &ru__litbrl__detailed__utb_size },
	{ "ru-litbrl.ctb",ru__litbrl__ctb, &ru__litbrl__ctb_size },
	{ "ru-ru-g1.ctb",ru__ru__g1__ctb, &ru__ru__g1__ctb_size },
	{ "ru-unicode.dis",ru__unicode__dis, &ru__unicode__dis_size },
	{ "ru.ctb",ru__ctb, &ru__ctb_size },
	{ "rw-rw-g1.utb",rw__rw__g1__utb, &rw__rw__g1__utb_size },
	{ "sa-in-g1.utb",sa__in__g1__utb, &sa__in__g1__utb_size },
	{ "sa.tbl",sa__tbl, &sa__tbl_size },
	{ "sah.utb",sah__utb, &sah__utb_size },
	{ "sd.tbl",sd__tbl, &sd__tbl_size },
	{ "se-se.ctb",se__se__ctb, &se__se__ctb_size },
	{ "se-se.dis",se__se__dis, &se__se__dis_size },
	{ "si-in-g1.utb",si__in__g1__utb, &si__in__g1__utb_size },
	{ "sin.cti",sin__cti, &sin__cti_size },
	{ "sin.utb",sin__utb, &sin__utb_size },
	{ "sk-g1.ctb",sk__g1__ctb, &sk__g1__ctb_size },
	{ "sk-sk-g1.utb",sk__sk__g1__utb, &sk__sk__g1__utb_size },
	{ "sk-sk.utb",sk__sk__utb, &sk__sk__utb_size },
	{ "sl-si-comp8.ctb",sl__si__comp8__ctb, &sl__si__comp8__ctb_size },
	{ "sl-si-g1.utb",sl__si__g1__utb, &sl__si__g1__utb_size },
	{ "sl.tbl",sl__tbl, &sl__tbl_size },
	{ "sot-za-g1.ctb",sot__za__g1__ctb, &sot__za__g1__ctb_size },
	{ "sot-za-g2.ctb",sot__za__g2__ctb, &sot__za__g2__ctb_size },
	{ "spaces.uti",spaces__uti, &spaces__uti_size },
	{ "sr-chardefs.cti",sr__chardefs__cti, &sr__chardefs__cti_size },
	{ "sr-g1.ctb",sr__g1__ctb, &sr__g1__ctb_size },
	{ "sr.tbl",sr__tbl, &sr__tbl_size },
	{ "sv-1989.ctb",sv__1989__ctb, &sv__1989__ctb_size },
	{ "sv-1996.ctb",sv__1996__ctb, &sv__1996__ctb_size },
	{ "sv-g0.utb",sv__g0__utb, &sv__g0__utb_size },
	{ "sv-g1.ctb",sv__g1__ctb, &sv__g1__ctb_size },
	{ "sv-g2.ctb",sv__g2__ctb, &sv__g2__ctb_size },
	{ "sw-ke-g1-2.ctb",sw__ke__g1__2__ctb, &sw__ke__g1__2__ctb_size },
	{ "sw-ke-g1-3.ctb",sw__ke__g1__3__ctb, &sw__ke__g1__3__ctb_size },
	{ "sw-ke-g1-4.ctb",sw__ke__g1__4__ctb, &sw__ke__g1__4__ctb_size },
	{ "sw-ke-g1-5.ctb",sw__ke__g1__5__ctb, &sw__ke__g1__5__ctb_size },
	{ "sw-ke-g1.utb",sw__ke__g1__utb, &sw__ke__g1__utb_size },
	{ "sw-ke-g2.ctb",sw__ke__g2__ctb, &sw__ke__g2__ctb_size },
	{ "ta-ta-g1.ctb",ta__ta__g1__ctb, &ta__ta__g1__ctb_size },
	{ "ta.ctb",ta__ctb, &ta__ctb_size },
	{ "ta.tbl",ta__tbl, &ta__tbl_size },
	{ "tamil.cti",tamil__cti, &tamil__cti_size },
	{ "te-in-g1.utb",te__in__g1__utb, &te__in__g1__utb_size },
	{ "te.tbl",te__tbl, &te__tbl_size },
	{ "telugu.cti",telugu__cti, &telugu__cti_size },
	{ "text_nabcc.dis",text_nabcc__dis, &text_nabcc__dis_size },
	{ "tr-g1.ctb",tr__g1__ctb, &tr__g1__ctb_size },
	{ "tr-g2.ctb",tr__g2__ctb, &tr__g2__ctb_size },
	{ "tr-g2.tbl",tr__g2__tbl, &tr__g2__tbl_size },
	{ "tr.ctb",tr__ctb, &tr__ctb_size },
	{ "tr.tbl",tr__tbl, &tr__tbl_size },
	{ "tsn-za-g1.ctb",tsn__za__g1__ctb, &tsn__za__g1__ctb_size },
	{ "tsn-za-g2.ctb",tsn__za__g2__ctb, &tsn__za__g2__ctb_size },
	{ "tt.utb",tt__utb, &tt__utb_size },
	{ "uk-comp.utb",uk__comp__utb, &uk__comp__utb_size },
	{ "uk.utb",uk__utb, &uk__utb_size },
	{ "ukchardefs.cti",ukchardefs__cti, &ukchardefs__cti_size },
	{ "ukmaths_single_cell_defs.cti",ukmaths_single_cell_defs__cti, &ukmaths_single_cell_defs__cti_size },
	{ "ukmaths_unicode_defs.cti",ukmaths_unicode_defs__cti, &ukmaths_unicode_defs__cti_size },
	{ "uni-text.dis",uni__text__dis, &uni__text__dis_size },
	{ "unicode-braille.utb",unicode__braille__utb, &unicode__braille__utb_size },
	{ "unicode-without-blank.dis",unicode__without__blank__dis, &unicode__without__blank__dis_size },
	{ "unicode.dis",unicode__dis, &unicode__dis_size },
	{ "ur-pk-g1.utb",ur__pk__g1__utb, &ur__pk__g1__utb_size },
	{ "ur-pk-g2.ctb",ur__pk__g2__ctb, &ur__pk__g2__ctb_size },
	{ "us-table.dis",us__table__dis, &us__table__dis_size },
	{ "uz-g1.utb",uz__g1__utb, &uz__g1__utb_size },
	{ "ve-za-g1.utb",ve__za__g1__utb, &ve__za__g1__utb_size },
	{ "ve-za-g2.ctb",ve__za__g2__ctb, &ve__za__g2__ctb_size },
	{ "vi-cb8.utb",vi__cb8__utb, &vi__cb8__utb_size },
	{ "vi-charsdef.uti",vi__charsdef__uti, &vi__charsdef__uti_size },
	{ "vi-lettersdef.uti",vi__lettersdef__uti, &vi__lettersdef__uti_size },
	{ "vi-puncsdef.uti",vi__puncsdef__uti, &vi__puncsdef__uti_size },
	{ "vi-saigon-g1.ctb",vi__saigon__g1__ctb, &vi__saigon__g1__ctb_size },
	{ "vi-vn-g0.utb",vi__vn__g0__utb, &vi__vn__g0__utb_size },
	{ "vi-vn-g1.ctb",vi__vn__g1__ctb, &vi__vn__g1__ctb_size },
	{ "vi-vn-g2.ctb",vi__vn__g2__ctb, &vi__vn__g2__ctb_size },
	{ "wiskunde-chardefs.cti",wiskunde__chardefs__cti, &wiskunde__chardefs__cti_size },
	{ "wordcx.dis",wordcx__dis, &wordcx__dis_size },
	{ "xh-za-g1.utb",xh__za__g1__utb, &xh__za__g1__utb_size },
	{ "xh-za-g2.ctb",xh__za__g2__ctb, &xh__za__g2__ctb_size },
	{ "zh-chn.ctb",zh__chn__ctb, &zh__chn__ctb_size },
	{ "zh-hk.ctb",zh__hk__ctb, &zh__hk__ctb_size },
	{ "zh-tw.ctb",zh__tw__ctb, &zh__tw__ctb_size },
	{ "zh_CHN.tbl",zh_CHN__tbl, &zh_CHN__tbl_size },
	{ "zh_HK.tbl",zh_HK__tbl, &zh_HK__tbl_size },
	{ "zhcn-cbs.ctb",zhcn__cbs__ctb, &zhcn__cbs__ctb_size },
	{ "zhcn-g1.ctb",zhcn__g1__ctb, &zhcn__g1__ctb_size },
	{ "zhcn-g2.ctb",zhcn__g2__ctb, &zhcn__g2__ctb_size },
	{ "zu-za-g1.utb",zu__za__g1__utb, &zu__za__g1__utb_size },
	{ "zu-za-g2.ctb",zu__za__g2__ctb, &zu__za__g2__ctb_size },
};


lou_dbfile_info lou_database_info[] = {
	{ "afr-za-g1.ctb","Afrikaans uncontracted braille","af","",0x0000, },
	{ "afr-za-g2.ctb","Afrikaans contracted braille","af","",0x0000, },
	{ "ar-ar-comp8.utb","Arabic computer braille","ar","",0x0001, },
	{ "ar-ar-g2.ctb","Arabic contracted braille","ar","",0x0000, },
	{ "ar.tbl","Arabic uncontracted braille","ar","",0x0000, },
	{ "as.tbl","Assamese braille","as","",0x0000, },
	{ "awa.tbl","Awadhi braille","awa","",0x0000, },
	{ "ba.utb","Bashkir braille","ba","",0x0000, },
	{ "bel-comp.utb","Belarusian computer braille","be","",0x0001, },
	{ "bel.utb","Belarusian braille","be","",0x0000, },
	{ "bg.tbl","Bulgarian computer braille","bg","",0x0001, },
	{ "bg.utb","Bulgarian braille","bg","",0x0000, },
	{ "bh.tbl","Bihari braille","bh","",0x0000, },
	{ "bn.tbl","Bengali braille","bn","",0x0000, },
	{ "bo.tbl","Tibetan computer braille","bo","",0x0001, },
	{ "bra.tbl","Braj braille","bra","",0x0000, },
	{ "ca.tbl","Catalan braille","ca","",0x0000, },
	{ "chr-us-g1.ctb","Cherokee braille","chr","",0x0000, },
	{ "ckb.tbl","Kurdish braille","ckb","",0x0000, },
	{ "cop-eg-comp8.utb","Coptic computer braille","cop","",0x0001, },
	{ "cs-comp8.utb","Czech computer braille","cs","",0x0001, },
	{ "cs.tbl","Czech braille","cs","",0x0000, },
	{ "cy-cy-g1.utb","Welsh uncontracted braille","cy","",0x0000, },
	{ "cy.tbl","Welsh contracted braille","cy","",0x0000, },
	{ "da-dk-g08.ctb","Danish computer braille (2022 standard)","da","",0x0001, },
	{ "da-dk-g08_1993.ctb","Danish computer braille (1993 standard)","da","",0x0001, },
	{ "da-dk-g16-lit_1993.ctb","Danish 6-dot uncontracted braille (1993 standard)","da","",0x0000, },
	{ "da-dk-g16.ctb","Danish 6-dot uncontracted braille (2022 standard)","da","",0x0000, },
	{ "da-dk-g16_1993.ctb","Danish 6-dot uncontracted braille (1993 standard)","da","",0x0000, },
	{ "da-dk-g18.ctb","Danish 8-dot uncontracted braille (2022 standard)","da","",0x0000, },
	{ "da-dk-g18_1993.ctb","Danish 8-dot uncontracted braille (1993 standard)","da","",0x0000, },
	{ "da-dk-g26-lit_1993.ctb","Danish 6-dot contracted braille (1993 standard)","da","",0x0000, },
	{ "da-dk-g26.ctb","Danish 6-dot contracted braille (2022 standard)","da","",0x0000, },
	{ "da-dk-g26_1993.ctb","Danish 6-dot contracted braille (1993 standard)","da","",0x0000, },
	{ "da-dk-g26l-lit_1993.ctb","Danish 6-dot partially contracted braille (1993 standard)","da","",0x0000, },
	{ "da-dk-g26l_1993.ctb","Danish 6-dot partially contracted braille (1993 standard)","da","",0x0000, },
	{ "da-dk-g28.ctb","Danish 8-dot contracted braille (2022 standard)","da","",0x0000, },
	{ "da-dk-g28_1993.ctb","Danish 8-dot contracted braille (1993 standard)","da","",0x0000, },
	{ "da-dk-g28l_1993.ctb","Danish 8-dot partially contracted braille (1993 standard)","da","",0x0000, },
	{ "de-comp6.utb","German 6-dot computer braille","de","",0x0001, },
	{ "de-de-comp8.ctb","German 8-dot computer braille","de","",0x0001, },
	{ "de-g0-detailed.utb","German uncontracted braille with indication of capitals","de","",0x0000, },
	{ "de-g0.utb","German uncontracted braille","de","",0x0000, },
	{ "de-g1-detailed.ctb","German partially contracted braille with indication of capitals","de","",0x0000, },
	{ "de-g1.ctb","German partially contracted braille","de","",0x0000, },
	{ "de-g2-detailed.ctb","German contracted braille with indication of capitals","de","",0x0000, },
	{ "de-g2.ctb","German contracted braille","de","",0x0000, },
	{ "dra.tbl","Dravidian computer braille","dra","",0x0001, },
	{ "el.ctb","Greek braille","el","",0x0000, },
	{ "en-gb-comp8.ctb","English computer braille as used in the U.K.","en","en-GB",0x0001, },
	{ "en-gb-g1.utb","English uncontracted braille as used in the U.K.","en","en-GB",0x0000, },
	{ "en-nabcc.utb","North American Braille Computer Code","en","",0x0001, },
	{ "en-ueb-g1.ctb","Unified English uncontracted braille","en","",0x0000, },
	{ "en-ueb-g2.ctb","Unified English contracted braille","en","",0x0000, },
	{ "en-us-comp6.ctb","English 6-dot computer braille as used in the U.S.","en","en-US",0x0001, },
	{ "en-us-g1.ctb","English uncontracted braille as used in the U.S.","en","en-US",0x0000, },
	{ "en_CA.tbl","English computer braille as used in Canada","en","en-CA",0x0001, },
	{ "en_GB.tbl","English contracted braille as used in the U.K.","en","en-GB",0x0000, },
	{ "en_US-comp8-ext.tbl","English 8-dot computer braille as used in the U.S.","en","en-US",0x0001, },
	{ "en_US.tbl","English contracted braille as used in the U.S.","en","en-US",0x0000, },
	{ "eo-g1-x-system.ctb","Esperanto x-system braille","eo-xsistemo","",0x0000, },
	{ "eo.tbl","Esperanto braille","eo","",0x0000, },
	{ "Es-Es-G0.utb","Spanish computer braille","es","",0x0001, },
	{ "es-g2.ctb","Spanish contracted braille","es","",0x0000, },
	{ "es.tbl","Spanish uncontracted braille","es","",0x0000, },
	{ "et.tbl","Estonian computer braille","et","",0x0001, },
	{ "fa-ir-comp8.ctb","Persian computer braille","fa","",0x0001, },
	{ "fa-ir-g1.utb","Persian braille","fa","",0x0000, },
	{ "fi-fi-8dot.ctb","Finnish computer braille","fi","",0x0001, },
	{ "fi.utb","Finnish braille","fi","",0x0000, },
	{ "fr-bfu-comp6.utb","French uncontracted braille","fr","",0x0000, },
	{ "fr-bfu-comp8.utb","French computer braille","fr","",0x0001, },
	{ "fr-bfu-g2.ctb","French contracted braille","fr","",0x0000, },
	{ "ga-g1.utb","Irish uncontracted braille","ga","",0x0000, },
	{ "ga-g2.ctb","Irish contracted braille","ga","",0x0000, },
	{ "gd.tbl","Scottish Gaelic computer braille","gd","",0x0001, },
	{ "gez.tbl","Ethiopic braille","gez","",0x0000, },
	{ "gon.tbl","Gondi braille","gon","",0x0000, },
	{ "grc-international-en.utb","Greek internationalized braille as used by English speakers","grc","en",0x0000, },
	{ "gu.tbl","Gujarati braille","gu","",0x0000, },
	{ "haw-us-g1.ctb","Hawaiian braille","haw","",0x0000, },
	{ "he-IL-comp8.utb","Hebrew computer braille","he","",0x0001, },
	{ "he-IL.utb","Israeli braille","en","mul-IL",0x0000, },
	{ "hi.tbl","Hindi braille","hi","",0x0000, },
	{ "hr-comp8.tbl","Croatian computer braille","hr","",0x0001, },
	{ "hr-g1.tbl","Croatian braille","hr","",0x0000, },
	{ "hu-hu-comp8.ctb","Hungarian computer braille","hu","",0x0001, },
	{ "hu-hu-g2.ctb","Hungarian contracted braille","hu","",0x0000, },
	{ "hu.tbl","Hungarian partially contracted braille","hu","",0x0000, },
	{ "hy.tbl","Armenian computer braille","hy","",0x0001, },
	{ "is.tbl","Icelandic braille","is","",0x0000, },
	{ "it-it-comp8.utb","Italian computer braille","it","",0x0001, },
	{ "it.tbl","Italian braille","it","",0x0000, },
	{ "iu-ca-g1.ctb","Inuktitut braille","iu","",0x0000, },
	{ "ja-kantenji.utb","Kantenji","ja","",0x0000, },
	{ "ka.utb","Georgian braille","ka","",0x0000, },
	{ "kha.tbl","Khasi braille","kha","",0x0000, },
	{ "kk.utb","Kazakh braille","kk","",0x0000, },
	{ "km-g1.utb","Khmer braille","km","",0x0000, },
	{ "kmr.tbl","Northern Kurdish braille","kmr","",0x0000, },
	{ "kn.tbl","Kannada braille","kn","",0x0000, },
	{ "ko-2006-g1.ctb","Korean uncontracted braille (2006 standard)","ko","",0x0000, },
	{ "ko-2006-g2.ctb","Korean contracted braille (2006 standard)","ko","",0x0000, },
	{ "ko-g1.ctb","Korean uncontracted braille","ko","",0x0000, },
	{ "ko-g2.ctb","Korean contracted braille","ko","",0x0000, },
	{ "kok.tbl","Konkani braille","kok","",0x0000, },
	{ "kru.tbl","Kurukh braille","kru","",0x0000, },
	{ "lg-ug-g1.utb","Luganda braille","lg","",0x0000, },
	{ "lt-6dot.tbl","Lithuanian 6-dot braille","lt","",0x0000, },
	{ "lt.tbl","Lithuanian 8-dot braille","lt","",0x0000, },
	{ "lv.tbl","Latvian braille","lv","",0x0000, },
	{ "mao-nz-g1.ctb","Maori braille","mi","",0x0000, },
	{ "ml.tbl","Malayalam braille","ml","",0x0000, },
	{ "mn-MN-g1.utb","Mongolian uncontracted braille","mn","",0x0000, },
	{ "mn-MN-g2.ctb","Mongolian contracted braille","mn","",0x0000, },
	{ "mni.tbl","Manipuri braille","mni","",0x0000, },
	{ "mr.tbl","Marathi braille","mr","",0x0000, },
	{ "ms-my-g2.ctb","Malay braille","ms","",0x0000, },
	{ "mt.tbl","Maltese computer braille","mt","",0x0001, },
	{ "mun.tbl","Munda braille","mun","",0x0000, },
	{ "mwr.tbl","Marwari braille","mwr","",0x0000, },
	{ "my-g1.utb","Burmese uncontracted braille","my","",0x0000, },
	{ "my-g2.ctb","Burmese contracted braille","my","",0x0000, },
	{ "ne.tbl","Nepali braille","ne","",0x0000, },
	{ "nl-comp8.utb","Dutch computer braille","nl","",0x0001, },
	{ "nl.tbl","Dutch braille","nl","",0x0000, },
	{ "no-no-8dot-fallback-6dot-g0.utb","Norwegian 8-dot uncontracted braille with 6-dot fallback","nn","",0x0000, },
	{ "no-no-8dot.utb","Norwegian 8-dot uncontracted braille","nn","",0x0000, },
	{ "no-no-comp8.ctb","Norwegian computer braille","nn","",0x0001, },
	{ "no-no-g0.utb","Norwegian 6-dot uncontracted braille","nn","",0x0000, },
	{ "no-no-g1.ctb","Norwegian grade 1 contracted braille","nn","",0x0000, },
	{ "no-no-g2.ctb","Norwegian grade 2 contracted braille","nn","",0x0000, },
	{ "no-no-g3.ctb","Norwegian grade 3 contracted braille","nn","",0x0000, },
	{ "nso-za-g1.utb","Sepedi uncontracted braille","nso","",0x0000, },
	{ "nso-za-g2.ctb","Sepedi contracted braille","nso","",0x0000, },
	{ "ny-mw.utb","Chichewa braille","ny","",0x0000, },
	{ "or.tbl","Oriya braille","or","",0x0000, },
	{ "pa.tbl","Punjabi braille","pa","",0x0000, },
	{ "pi.tbl","Pali braille","pi","",0x0000, },
	{ "pl-pl-comp8.ctb","Polish computer braille","pl","",0x0001, },
	{ "pl.tbl","Polish braille","pl","",0x0000, },
	{ "pt-pt-comp8.ctb","Portuguese computer braille","pt","",0x0001, },
	{ "pt-pt-g1.utb","Portuguese uncontracted braille","pt","",0x0000, },
	{ "pt.tbl","Portuguese contracted braille","pt","",0x0000, },
	{ "ro.tbl","Romanian computer braille","ro","",0x0001, },
	{ "ru-compbrl.ctb","Russian braille for program sources","ru","",0x0000, },
	{ "ru-litbrl-detailed.utb","Russian braille with indication of capitals","ru","",0x0000, },
	{ "ru-litbrl.ctb","Russian braille","ru","",0x0000, },
	{ "ru-ru-g1.ctb","Russian contracted braille","ru","",0x0000, },
	{ "ru.ctb","Russian computer braille","ru","",0x0001, },
	{ "rw-rw-g1.utb","Kinyarwanda braille","rw","",0x0000, },
	{ "sa.tbl","Sanskrit braille","sa","",0x0000, },
	{ "sah.utb","Yakut braille","sah","",0x0000, },
	{ "sd.tbl","Sindhi braille","sd","",0x0000, },
	{ "sk-g1.ctb","Slovak braille","sk","",0x0000, },
	{ "sl-si-comp8.ctb","Slovenian computer braille","sl","",0x0001, },
	{ "sl.tbl","Slovenian braille","sl","",0x0000, },
	{ "sot-za-g1.ctb","Sesotho uncontracted braille","st","",0x0000, },
	{ "sot-za-g2.ctb","Sesotho contracted braille","st","",0x0000, },
	{ "sr.tbl","Serbian braille","sr","",0x0000, },
	{ "sv-1989.ctb","Swedish computer braille (1989 standard)","sv","",0x0001, },
	{ "sv-1996.ctb","Swedish computer braille (1996 standard)","sv","",0x0001, },
	{ "sv-g0.utb","Swedish uncontracted braille","sv","",0x0000, },
	{ "sv-g1.ctb","Swedish partially contracted braille","sv","",0x0000, },
	{ "sv-g2.ctb","Swedish contracted braille","sv","",0x0000, },
	{ "sw-ke-g1-2.ctb","Swahili grade 1.2 contracted braille","sw","sw-KE",0x0000, },
	{ "sw-ke-g1-3.ctb","Swahili grade 1.3 contracted braille","sw","sw-KE",0x0000, },
	{ "sw-ke-g1-4.ctb","Swahili grade 1.4 contracted braille","sw","sw-KE",0x0000, },
	{ "sw-ke-g1-5.ctb","Swahili grade 1.5 contracted braille","sw","sw-KE",0x0000, },
	{ "sw-ke-g1.utb","Swahili uncontracted braille","sw","sw-KE",0x0000, },
	{ "sw-ke-g2.ctb","Swahili grade 2 contracted braille","sw","sw-KE",0x0000, },
	{ "ta-ta-g1.ctb","Tamil braille","ta","",0x0000, },
	{ "ta.tbl","Tamil computer braille","ta","",0x0001, },
	{ "te.tbl","Telugu braille","te","",0x0000, },
	{ "tr-g2.tbl","Turkish braille","tr","",0x0000, },
	{ "tr.tbl","Turkish computer braille","tr","",0x0001, },
	{ "tsn-za-g1.ctb","Setswana uncontracted braille","tn","",0x0000, },
	{ "tsn-za-g2.ctb","Setswana contracted braille","tn","",0x0000, },
	{ "tt.utb","Tatar braille","tt","",0x0000, },
	{ "uk-comp.utb","Ukrainian computer braille","uk","",0x0001, },
	{ "uk.utb","Ukrainian braille","uk","",0x0000, },
	{ "ur-pk-g1.utb","Urdu uncontracted braille","ur","",0x0000, },
	{ "ur-pk-g2.ctb","Urdu contracted braille","ur","",0x0000, },
	{ "uz-g1.utb","Uzbek braille","uz","",0x0000, },
	{ "ve-za-g1.utb","Tshivenda uncontracted braille","ve","",0x0000, },
	{ "ve-za-g2.ctb","Tshivenda contracted braille","ve","",0x0000, },
	{ "vi-cb8.utb","Vietnamese computer braille","vi","",0x0001, },
	{ "vi-saigon-g1.ctb","Vietnamese Saigon braille","vi","",0x0000, },
	{ "vi-vn-g0.utb","Vietnamese uncontracted braille","vi","",0x0000, },
	{ "vi-vn-g1.ctb","Vietnamese partially contracted braille","vi","",0x0000, },
	{ "vi-vn-g2.ctb","Vietnamese contracted braille","vi","",0x0000, },
	{ "xh-za-g1.utb","isiXhosa uncontracted braille","xh","",0x0000, },
	{ "xh-za-g2.ctb","isiXhosa contracted braille","xh","",0x0000, },
	{ "zh-tw.ctb","Taiwanese bopomofo braille","cmn","cmn-TW",0x0000, },
	{ "zh_CHN.tbl","Chinese current braille without tones, for simplified Chinese characters","cmn-Hans","cmn-CN",0x0000, },
	{ "zh_HK.tbl","Cantonese braille","yue","yue-HK",0x0000, },
	{ "zhcn-cbs.ctb","Chinese common braille, for simplified Chinese characters","cmn-Hans","cmn-CN",0x0000, },
	{ "zhcn-g1.ctb","Chinese current braille with tones","cmn","cmn-CN",0x0000, },
	{ "zhcn-g2.ctb","Chinese double-phonic braille","cmn","cmn-CN",0x0000, },
	{ "zu-za-g1.utb","isiZulu uncontracted braille","zu","",0x0000, },
	{ "zu-za-g2.ctb","isiZulu contracted braille","zu","",0x0000, },
};


lou_dbfile_info lou_database_display[] = {
	{ "bg.dis","","","",0x0 },
	{ "da-dk-octobraille.dis","","","",0x0 },
	{ "da-dk-octobraille_1993.dis","","","",0x0 },
	{ "de-de.dis","","","",0x0 },
	{ "de-eurobrl6.dis","","","",0x0 },
	{ "de-eurobrl6u.dis","","","",0x0 },
	{ "en-us-brf.dis","","","",0x0 },
	{ "es-new.dis","","","",0x0 },
	{ "es-old.dis","","","",0x0 },
	{ "hu-backtranslate-correction.dis","","","",0x0 },
	{ "nl-BE.dis","","","",0x0 },
	{ "no-no-braillo-047-01.dis","","","",0x0 },
	{ "no-no-generic.dis","","","",0x0 },
	{ "no-no.dis","","","",0x0 },
	{ "ru-brf.dis","","","",0x0 },
	{ "ru-letters.dis","","","",0x0 },
	{ "ru-unicode.dis","","","",0x0 },
	{ "se-se.dis","","","",0x0 },
	{ "text_nabcc.dis","","","",0x0 },
	{ "uni-text.dis","","","",0x0 },
	{ "unicode-without-blank.dis","","","",0x0 },
	{ "unicode.dis","","","",0x0 },
	{ "us-table.dis","","","",0x0 },
	{ "wordcx.dis","","","",0x0 },
};


