import sys
import os
import json
import glob

NBCOL = 8

def pathtovar (path):
    vname = os.path.basename(path)
    vname = vname.replace(".", "__")
    vname = vname.replace("-", "__")
    return vname

def write_header (stream, filename):
    stream.write ("// Autogenerated file\n")
    stream.write ("// Do not manually modify\n")
    stream.write ("// file:{0}\n".format(filename))
    stream.write ("\n")
    stream.write ("\n")

def write_start (stream, filename):    
    stream.write ("#include <stdio.h>\n")
    stream.write ("#include <stdlib.h>\n")

    stream.write ("#ifdef __EMSCRIPTEN__\n")
    stream.write ("#include \"emscripten.h\"\n")
    stream.write ("#define EXPORT_CALL EMSCRIPTEN_KEEPALIVE\n")
    
    stream.write ("#endif\n")
    stream.write ("\n")
        
def file2c (pathfrom, pathto, varname, filename):
    with open(pathfrom,"rb") as fin:
        data = fin.read ()
    
    with open (pathto, "w") as fout:
        write_header(fout, filename)
        write_start(fout, filename)

        fout.write ("uint8_t {0}[]".format(varname))
        fout.write ("={\n")
        size = len(data)
        col = 0
        for i in range (size):
            fout.write ("0x{:02x}".format (data[i]))
            if i != size - 1:
                if i % NBCOL == 0 and  i > 0:
                    fout.write (",\n")
                else:
                    fout.write (",")
            else:
                fout.write ("\n")
        fout.write ("};\n")
        fout.write ("size_t {0}_size=sizeof({0});\n".format(varname))

def build_database (generated, header, implement, dbname, dbtype):
    with open (header, "w") as fout:
        write_header(fout, header)
        fout.write ("\n")
        fout.write ("#ifndef\t__{0}_H\n".format(os.path.basename(header).upper().replace('.','_')))
        fout.write ("#define\t__{0}_H\n".format(os.path.basename(header).upper().replace('.','_')))
        fout.write ("\n")
        fout.write ("\n")
        fout.write ("#define\t{0}_NBR\t{1}\n".format(dbtype.upper(), len(generated)))
        fout.write ("\n")
        fout.write ("\n")
        fout.write ("typedef struct _{0}".format (dbtype))
        fout.write ("{\n")
        fout.write ("char *fname;\n")
        fout.write ("uint8_t* data;\n")
        fout.write ("size_t* size;\n")
        fout.write ("} ")
        fout.write ("{0};\n".format (dbtype))
        fout.write ("\n")
        fout.write ("\n")
        fout.write ("#endif")
        fout.write ("\n")
        fout.write ("\n")
        fout.write ("\n")
        
    with open (implement, "w") as fout:
        write_header(fout, implement)
        write_start(fout, implement)
        fout.write ("#include \"{0}\"\n".format (os.path.basename(header)))
        fout.write ("\n")
        fout.write ("\n")

        for f in generated:
            fout.write ("extern uint8_t {1}[];\n".format(dbtype, f["var"]))                
            fout.write ("extern size_t {0};\n".format(f["var"]+"_size"))                

        fout.write ("{0} {1}[] = ".format(dbtype, dbname))
        fout.write ("{\n")
        
        for f in generated:
            fout.write ("\t{ ")    
            fout.write ("\"{0}\",".format(f["filename"]))
            fout.write (" {0},".format(f["var"]))                
            fout.write (" &{0}".format(f["var"]+"_size"))                
            fout.write (" },\n")    
        fout.write ("};\n")

def build (path):
    data = {}
    with open(path) as f:
        data = json.load (f)
    
    root = ""
    if "srcdir" in data:
        root = data["srcdir"]
 
    if "f2c" in data:
        generated = []
        for filter in data["f2c"]:
            files = glob.glob (root+filter)
            for file in files:
                dst = data["dstdir"] + pathtovar(file)+".c"
                varname = pathtovar(file)
                filename = os.path.basename(file)
           
                print (file, dst)
                file2c (file, dst, varname, filename)
                generated.append ({"filename":filename, "var":varname, "src":file, "dst":dst })

        
        generated.sort(key=lambda filedata: filedata["filename"])
        build_database (generated, data["db_header"], data["db_implement"], data["db_name"], data["db_type"])

if __name__ == "__main__":
    #file2c (sys.argv[1], sys.argv[2])
    build (sys.argv[1])
