import sys


def file2c (pathfrom, pathto):
    with open(pathfrom,"rb") as fin:
        data = fin.read ()
    
    with open (pathto, "w") as fout:
        fout.writeln ("// Autogenerated file")
        fout.writeln ("// Do not manually modify")
        fout.writeln ("")
        fout.writeln ("")
        fout.writeln ("uint8_t data[]={")
        size = len(data)
        col = 0
        for i in range (size)
            fout.write ("0x{:02x}".format (data[i]))
            if i != size - 1:
                if i % NBCOL == 0:
                    fout.writeln (",")
                else
                    fout.write (",")
        fout.writeln ("};")

if __name__ == "__main__":
    file2c (sys.argv[1], sys.argv[2])
    
