  - name: Setup Emscripten toolchain
    # You may pin to the exact commit or the version.
    # uses: mymindstorm/setup-emsdk@ab889da2abbcbb280f91ec4c215d3bb4f3a8f775
    uses: mymindstorm/setup-emsdk@v12
    with:
      # Version to install
      version: # optional, default is latest
      # If true will not download any version of Emscripten. emsdk will still be added to PATH.
      no-install: # optional
      # If true will not cache any downloads with tc.cacheDir.
      no-cache: # optional
      # Directory to cache emsdk in. This folder will go under $GITHUB_HOME (I.e. build dir) and be cached using @actions/cache.
      actions-cache-folder: # optional, default is 
      # Fetch package information for all the new tools and SDK versions
      update: # optional
      # Deprecated in favor of `update`.
      update-tags: # optional
